import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :tcg_cheap, TcgCheap.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: String.to_integer(System.get_env("DB_PORT", "5436")),
  url: System.get_env("DATABASE_URL", "ecto://postgres:postgres@localhost:5436/tcg_cheap_dev"),
  database: "tcg_cheap_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tcg_cheap, TcgCheapWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4004],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "RA6gZTR7RRXE6HG8w+/6rS388ID7Fi5Sm9c0FZNCz4kY5tQczQuMi3BpLIPqCICE",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tcg_cheap, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tcg_cheap, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :tcg_cheap, dev_routes: true

# Development-only/manual-test adapter registry; no Cron is enabled for it.
config :tcg_cheap, :sealed_retailer_adapters, %{
  "lootquest" => %{
    adapter: TcgCheap.Catalogue.SealedRetailers.LootQuest,
    options: [per_page: 100, max_pages: 10]
  },
  "cardzhouse" => %{
    adapter: TcgCheap.Catalogue.SealedRetailers.CardzHouse,
    options: [per_page: 100, max_pages: 10]
  },
  "boosterpoint" => %{
    adapter: TcgCheap.Catalogue.SealedRetailers.BoosterPoint,
    options: [per_page: 100, max_pages: 10]
  }
}

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
