defmodule TcgCheap.Repo.Migrations.ResumableCatalogueSync do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalogue_sync_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_key, :text, null: false
      add :set_ids, {:array, :text}, null: false
      add :next_index, :bigint, null: false, default: 0
      add :synced_sets, :bigint, null: false, default: 0
      add :failed_sets, :bigint, null: false, default: 0
      add :excluded_sets, :bigint, null: false, default: 0
      add :status, :text, null: false, default: "running"
      add :started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:catalogue_sync_runs, [:provider_key], unique: true, where: "status = 'running'")

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_operation_invariant)

    create constraint(:acquisition_runs, :acquisition_runs_operation_invariant,
             check: """
               operation IN ('single_valuation','exchange_rate','sealed_retailer_refresh','card_catalogue_sync')
             """
           )

    create constraint(:catalogue_sync_runs, :catalogue_sync_runs_provider_invariant,
             check: """
               provider_key = 'tcgdex_catalogue'
             """
           )

    create constraint(:catalogue_sync_runs, :catalogue_sync_runs_set_ids_invariant,
             check: """
               cardinality(set_ids) BETWEEN 1 AND 1000 AND array_position(set_ids, NULL) IS NULL AND array_to_string(set_ids, ',') ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}(,[A-Za-z0-9][A-Za-z0-9._-]{0,127})*$'
             """
           )

    create constraint(:catalogue_sync_runs, :catalogue_sync_runs_index_invariant,
             check: """
               next_index >= 0 AND next_index <= cardinality(set_ids)
             """
           )

    create constraint(:catalogue_sync_runs, :catalogue_sync_runs_counter_invariant,
             check: """
               synced_sets >= 0 AND failed_sets >= 0 AND excluded_sets >= 0 AND synced_sets + failed_sets + excluded_sets = next_index
             """
           )

    create constraint(:catalogue_sync_runs, :catalogue_sync_runs_lifecycle_invariant,
             check: """
               (status = 'running' AND next_index < cardinality(set_ids) AND completed_at IS NULL) OR (status = 'completed' AND next_index = cardinality(set_ids) AND completed_at IS NOT NULL)
             """
           )

    create constraint(:catalogue_sync_runs, :catalogue_sync_runs_status_invariant,
             check: """
               status IN ('running','completed')
             """
           )

    create constraint(:catalogue_sync_runs, :catalogue_sync_runs_timestamp_invariant,
             check: """
               completed_at IS NULL OR completed_at >= started_at
             """
           )

    execute("""
    CREATE FUNCTION tcg_cheap_validate_catalogue_set_ids()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF NEW.set_ids <> ARRAY(
        SELECT set_id FROM unnest(NEW.set_ids) AS set_id ORDER BY set_id
      ) OR cardinality(NEW.set_ids) <> cardinality(ARRAY(
        SELECT DISTINCT set_id FROM unnest(NEW.set_ids) AS set_id
      )) THEN
        RAISE EXCEPTION USING
          ERRCODE = '23514',
          CONSTRAINT = 'catalogue_sync_runs_set_ids_canonical_invariant',
          MESSAGE = 'set_ids must be sorted and unique';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER catalogue_sync_runs_set_ids_canonical_trigger
    BEFORE INSERT OR UPDATE OF set_ids ON catalogue_sync_runs
    FOR EACH ROW EXECUTE FUNCTION tcg_cheap_validate_catalogue_set_ids();
    """)
  end

  def down do
    execute("""
    DROP TRIGGER catalogue_sync_runs_set_ids_canonical_trigger ON catalogue_sync_runs;
    """)

    execute("""
    DROP FUNCTION tcg_cheap_validate_catalogue_set_ids();
    """)

    drop_if_exists constraint(:catalogue_sync_runs, :catalogue_sync_runs_timestamp_invariant)

    drop_if_exists constraint(:catalogue_sync_runs, :catalogue_sync_runs_status_invariant)

    drop_if_exists constraint(:catalogue_sync_runs, :catalogue_sync_runs_lifecycle_invariant)

    drop_if_exists constraint(:catalogue_sync_runs, :catalogue_sync_runs_counter_invariant)

    drop_if_exists constraint(:catalogue_sync_runs, :catalogue_sync_runs_index_invariant)

    drop_if_exists constraint(:catalogue_sync_runs, :catalogue_sync_runs_set_ids_invariant)

    drop_if_exists constraint(:catalogue_sync_runs, :catalogue_sync_runs_provider_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_operation_invariant)

    # The previous schema cannot represent telemetry emitted by the removed worker.
    execute("DELETE FROM acquisition_runs WHERE operation = 'card_catalogue_sync'")

    create constraint(:acquisition_runs, :acquisition_runs_operation_invariant,
             check: """
               operation IN ('single_valuation','exchange_rate','sealed_retailer_refresh')
             """
           )

    drop_if_exists index(:catalogue_sync_runs, [:provider_key])

    drop table(:catalogue_sync_runs)
  end
end
