defmodule TcgCheap.Repo.Migrations.DurableCatalogueSetIssueResolution do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalogue_set_issue_resolutions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :set_id, :text, null: false
      add :mode, :text, null: false
      add :resolved_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:catalogue_set_issue_resolutions, [:set_id, :mode])

    create unique_index(:catalogue_set_issue_resolutions, [:set_id, :mode],
             name: "catalogue_set_issue_resolutions_identity"
           )

    create constraint(
             :catalogue_set_issue_resolutions,
             :catalogue_set_issue_resolutions_set_id_invariant,
             check: """
               btrim(set_id) <> '' AND set_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
             """
           )

    create constraint(
             :catalogue_set_issue_resolutions,
             :catalogue_set_issue_resolutions_mode_invariant,
             check: """
               mode IN ('hard','all')
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :catalogue_set_issue_resolutions,
                     :catalogue_set_issue_resolutions_mode_invariant
                   )

    drop_if_exists constraint(
                     :catalogue_set_issue_resolutions,
                     :catalogue_set_issue_resolutions_set_id_invariant
                   )

    drop_if_exists unique_index(:catalogue_set_issue_resolutions, [:set_id, :mode],
                     name: "catalogue_set_issue_resolutions_identity"
                   )

    drop_if_exists index(:catalogue_set_issue_resolutions, [:set_id, :mode])

    drop table(:catalogue_set_issue_resolutions)
  end
end
