defmodule TcgCheap.Repo.Migrations.HardenExternalUrlConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:retailer_listings, :retailer_listings_identity_invariant)

    create constraint(:retailer_listings, :retailer_listings_identity_invariant,
             check: """
               btrim(source_listing_id) <> '' AND btrim(source_title) <> '' AND btrim(normalized_title) <> '' AND direct_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'
             """
           )

    drop_if_exists constraint(:retailers, :retailers_homepage_url_invariant)

    create constraint(:retailers, :retailers_homepage_url_invariant,
             check: """
               homepage_url IS NULL OR homepage_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'
             """
           )

    drop_if_exists constraint(
                     :sealed_listing_observations,
                     :sealed_listing_observations_identity_invariant
                   )

    create constraint(
             :sealed_listing_observations,
             :sealed_listing_observations_identity_invariant,
             check: """
               btrim(source_title) <> '' AND btrim(normalized_title) <> '' AND direct_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'
             """
           )

    drop_if_exists constraint(:sealed_products, :sealed_products_official_price_invariant)

    drop_if_exists constraint(:sealed_products, :sealed_products_image_provenance_invariant)

    drop_if_exists constraint(:sealed_products, :sealed_products_details_provenance_invariant)

    create constraint(:sealed_products, :sealed_products_msrp_source_url_invariant,
             check: """
               msrp_source_url IS NULL OR msrp_source_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'
             """
           )

    create constraint(:sealed_products, :sealed_products_official_url_invariant,
             check: """
               official_url IS NULL OR official_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'
             """
           )

    create constraint(:sealed_products, :sealed_products_official_price_invariant,
             check: """
               ((official_price_amount IS NULL AND official_price_currency IS NULL AND official_price_source IS NULL AND official_price_source_url IS NULL) OR (official_price_amount IS NOT NULL AND official_price_currency IS NOT NULL AND official_price_source IS NOT NULL AND official_price_source_url IS NOT NULL AND official_price_amount > 0 AND official_price_amount <> 'NaN'::numeric AND official_price_amount <> 'Infinity'::numeric AND official_price_amount <> '-Infinity'::numeric AND official_price_currency IN ('PLN','USD','EUR') AND btrim(official_price_source) <> '' AND official_price_source_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'))
             """
           )

    create constraint(:sealed_products, :sealed_products_image_provenance_invariant,
             check: """
               ((image_url IS NULL AND image_source IS NULL AND image_source_url IS NULL) OR (image_url IS NOT NULL AND image_source IS NOT NULL AND image_source_url IS NOT NULL AND image_url ~* '^https://((assets\.tcgdex\.net|assets\.pokemon\.com|www\.pokemon\.com|mcdn\.pokemon\.com)|([a-z0-9-]+\.)*(lootquest\.pl|cardzhouse\.pl|boosterpoint\.pl|pokebooster\.pl|boosterland\.pl|colligere\.pl))(:443)?(/|[/?#][^[:space:][:cntrl:]]*)?$' AND btrim(image_source) <> '' AND image_source_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'))
             """
           )

    create constraint(:sealed_products, :sealed_products_details_provenance_invariant,
             check: """
               ((description IS NULL AND contents = '{}'::text[] AND pack_count IS NULL AND cards_per_pack IS NULL AND official_url IS NULL AND details_source IS NULL AND details_source_url IS NULL) OR (details_source IS NOT NULL AND details_source_url IS NOT NULL AND btrim(details_source) <> '' AND details_source_url ~* '^https://[^/:@?#[:space:][:cntrl:]]+(:[0-9]+)?(/|[/?#][^[:space:][:cntrl:]]*)?$'))
             """
           )
  end

  def down, do: raise("forward-only migration")
end
