defmodule TcgCheap.Repo.Migrations.SealedDailyAggregates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sealed_daily_aggregates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :aggregate_date, :date, null: false
      add :calculation_version, :text, null: false, default: "sealed_market_daily_v1"
      add :currency, :text, null: false, default: "PLN"
      add :status, :text, null: false
      add :limited_reason, :text
      add :benchmark_pln, :decimal
      add :typical_low_pln, :decimal
      add :typical_high_pln, :decimal
      add :fresh_regular_retailer_count, :bigint, null: false
      add :fresh_lgs_count, :bigint, null: false
      add :recent_sold_out_0_14_day_count, :bigint, null: false
      add :sold_out_15_30_day_count, :bigint, null: false
      add :stale_or_future_current_offer_count, :bigint, null: false
      add :unique_source_retailer_count, :bigint, null: false
      add :latest_nonfuture_checked_at, :utc_datetime_usec
      add :calculated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sealed_product_id,
          references(:sealed_products,
            column: :id,
            name: "sealed_daily_aggregates_sealed_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(
             :sealed_daily_aggregates,
             [:sealed_product_id, :aggregate_date, :calculation_version],
             name: "sealed_daily_aggregates_unique_product_date_version_index"
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_version_invariant,
             check: """
               calculation_version ~ '^sealed_market_daily_v[0-9]+$'
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_currency_invariant,
             check: """
               currency = 'PLN'
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_state_invariant,
             check: """
               (status = 'ready' AND limited_reason IS NULL AND benchmark_pln IS NOT NULL AND typical_low_pln IS NOT NULL AND typical_high_pln IS NOT NULL) OR (status = 'limited' AND limited_reason IN ('no_fresh_current_offers', 'too_few_regular_retailers', 'insufficient_inliers') AND benchmark_pln IS NULL AND typical_low_pln IS NULL AND typical_high_pln IS NULL)
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_price_invariant,
             check: """
               (benchmark_pln IS NULL OR (benchmark_pln > 0 AND benchmark_pln <> 'NaN'::numeric AND benchmark_pln <> 'Infinity'::numeric AND benchmark_pln <> '-Infinity'::numeric)) AND (typical_low_pln IS NULL OR (typical_low_pln > 0 AND typical_low_pln <> 'NaN'::numeric AND typical_low_pln <> 'Infinity'::numeric AND typical_low_pln <> '-Infinity'::numeric)) AND (typical_high_pln IS NULL OR (typical_high_pln > 0 AND typical_high_pln <> 'NaN'::numeric AND typical_high_pln <> 'Infinity'::numeric AND typical_high_pln <> '-Infinity'::numeric)) AND (benchmark_pln IS NULL OR (typical_low_pln <= benchmark_pln AND benchmark_pln <= typical_high_pln))
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_counts_invariant,
             check: """
               fresh_regular_retailer_count >= 0 AND fresh_lgs_count >= 0 AND recent_sold_out_0_14_day_count >= 0 AND sold_out_15_30_day_count >= 0 AND stale_or_future_current_offer_count >= 0 AND unique_source_retailer_count >= 0
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_time_invariant,
             check: """
               aggregate_date <= calculated_at::date
             """
           )
  end

  def down do
    drop_if_exists constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_time_invariant)

    drop_if_exists constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_counts_invariant)

    drop_if_exists constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_price_invariant)

    drop_if_exists constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_state_invariant)

    drop_if_exists constraint(
                     :sealed_daily_aggregates,
                     :sealed_daily_aggregates_currency_invariant
                   )

    drop_if_exists constraint(
                     :sealed_daily_aggregates,
                     :sealed_daily_aggregates_version_invariant
                   )

    drop constraint(:sealed_daily_aggregates, "sealed_daily_aggregates_sealed_product_id_fkey")

    drop_if_exists unique_index(
                     :sealed_daily_aggregates,
                     [:sealed_product_id, :aggregate_date, :calculation_version],
                     name: "sealed_daily_aggregates_unique_product_date_version_index"
                   )

    drop table(:sealed_daily_aggregates)
  end
end
