defmodule TcgCheap.Repo.Migrations.PersistedSealedGuideSources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sealed_daily_aggregates) do
      add :source_msrp_pln, :decimal
    end

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_time_invariant
                   )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_time_invariant,
             check: """
               guide_date <= source_aggregate_calculated_at::date AND source_aggregate_calculated_at <= calculated_at
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_source_msrp_invariant,
             check: """
               source_msrp_pln IS NULL OR (source_msrp_pln > 0 AND source_msrp_pln <> 'NaN'::numeric AND source_msrp_pln <> 'Infinity'::numeric AND source_msrp_pln <> '-Infinity'::numeric)
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :sealed_daily_aggregates,
                     :sealed_daily_aggregates_source_msrp_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_time_invariant
                   )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_time_invariant,
             check: """
               guide_date = source_aggregate_calculated_at::date AND source_aggregate_calculated_at <= calculated_at
             """
           )

    alter table(:sealed_daily_aggregates) do
      remove :source_msrp_pln
    end
  end
end
