defmodule TcgCheap.Repo.Migrations.AcquisitionObservability do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_source_health, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_key, :text, null: false
      add :last_started_at, :utc_datetime_usec, null: false
      add :last_succeeded_at, :utc_datetime_usec
      add :last_failed_at, :utc_datetime_usec
      add :last_status, :text
      add :last_failure_category, :text
      add :consecutive_failures, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:acquisition_source_health, [:provider_key],
             name: "acquisition_source_health_unique_provider_key_index"
           )

    create table(:acquisition_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :attempt_key, :text, null: false
      add :provider_key, :text, null: false
      add :operation, :text, null: false
      add :target_key, :text, null: false
      add :worker, :text, null: false
      add :queue, :text, null: false
      add :job_id, :bigint
      add :attempt, :bigint, null: false
      add :max_attempts, :bigint, null: false
      add :status, :text, null: false, default: "running"
      add :failure_category, :text
      add :request_count, :bigint, null: false, default: 0
      add :started_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:acquisition_runs, [:attempt_key],
             name: "acquisition_runs_unique_attempt_key_index"
           )

    create constraint(:acquisition_runs, :acquisition_runs_attempt_key_invariant,
             check: """
               btrim(attempt_key) <> ''
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_attempt_bounds,
             check: """
               attempt > 0 AND max_attempts > 0 AND attempt <= max_attempts
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_request_count_nonnegative,
             check: """
               request_count >= 0
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_lifecycle_invariant,
             check: """
               (status = 'running' AND finished_at IS NULL AND failure_category IS NULL) OR (status = 'succeeded' AND finished_at IS NOT NULL AND failure_category IS NULL) OR (status IN ('retryable_failure','cancelled') AND finished_at IS NOT NULL AND failure_category IS NOT NULL)
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_timestamp_invariant,
             check: """
               finished_at IS NULL OR finished_at >= started_at
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_status_invariant,
             check: """
               status IN ('running','succeeded','retryable_failure','cancelled')
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_failure_category_invariant,
             check: """
               failure_category IS NULL OR failure_category IN ('budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown')
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_operation_invariant,
             check: """
               operation IN ('single_valuation','exchange_rate','sealed_retailer_refresh')
             """
           )

    create constraint(:acquisition_source_health, :source_health_failures_nonnegative,
             check: """
               consecutive_failures >= 0
             """
           )

    create constraint(:acquisition_source_health, :source_health_state_invariant,
             check: """
               last_started_at IS NOT NULL AND ((last_status IS NULL AND last_succeeded_at IS NULL AND last_failed_at IS NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status = 'succeeded' AND last_succeeded_at IS NOT NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status IN ('retryable_failure','cancelled') AND last_failed_at IS NOT NULL AND last_failure_category IS NOT NULL AND consecutive_failures > 0))
             """
           )

    create constraint(:acquisition_source_health, :source_health_status_invariant,
             check: """
               last_status IS NULL OR last_status IN ('succeeded','retryable_failure','cancelled')
             """
           )

    create constraint(:acquisition_source_health, :source_health_failure_category_invariant,
             check: """
               last_failure_category IS NULL OR last_failure_category IN ('budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown')
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :acquisition_source_health,
                     :source_health_failure_category_invariant
                   )

    drop_if_exists constraint(:acquisition_source_health, :source_health_status_invariant)

    drop_if_exists constraint(:acquisition_source_health, :source_health_state_invariant)

    drop_if_exists constraint(:acquisition_source_health, :source_health_failures_nonnegative)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_operation_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_failure_category_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_status_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_timestamp_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_lifecycle_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_request_count_nonnegative)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_attempt_bounds)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_attempt_key_invariant)

    drop_if_exists unique_index(:acquisition_runs, [:attempt_key],
                     name: "acquisition_runs_unique_attempt_key_index"
                   )

    drop table(:acquisition_runs)

    drop_if_exists unique_index(:acquisition_source_health, [:provider_key],
                     name: "acquisition_source_health_unique_provider_key_index"
                   )

    drop table(:acquisition_source_health)
  end
end
