defmodule TcgCheap.Repo.Migrations.PersistedSealedGuideHardening do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sealed_daily_aggregates) do
      add :source_mapping_confident, :boolean, null: false, default: false
    end

    create index(:sealed_buying_guide_snapshots, [:source_aggregate_id])
  end

  def down do
    drop_if_exists index(:sealed_buying_guide_snapshots, [:source_aggregate_id])

    alter table(:sealed_daily_aggregates) do
      remove :source_mapping_confident
    end
  end
end
