defmodule TcgCheap.Repo.Migrations.AddCardPrintingValuations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:single_valuation_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value_eur, :decimal, null: false
      add :currency, :text, null: false, default: "EUR"
      add :policy_version, :text, null: false
      add :source, :text, null: false
      add :source_metric, :text, null: false
      add :fetched_at, :utc_datetime_usec, null: false
      add :provider_updated_at, :utc_datetime_usec
      add :cardmarket_product_id, :bigint
      add :current?, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :card_printing_id, :uuid, null: false
    end

    create index(:single_valuation_snapshots, [:card_printing_id, :policy_version],
             unique: true,
             where: "\"current?\" = TRUE"
           )

    create index(:single_valuation_snapshots, [:card_printing_id, :policy_version, :fetched_at])

    create table(:card_printings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:single_valuation_snapshots) do
      modify :card_printing_id,
             references(:card_printings,
               column: :id,
               name: "single_valuation_snapshots_card_printing_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:card_printings) do
      add :tcgdex_id, :text, null: false
      add :name, :text, null: false
      add :set_name, :text, null: false
      add :collector_number, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:card_printings, [:tcgdex_id],
             name: "card_printings_unique_tcgdex_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:card_printings, [:tcgdex_id],
                     name: "card_printings_unique_tcgdex_id_index"
                   )

    alter table(:card_printings) do
      remove :updated_at
      remove :created_at
      remove :collector_number
      remove :set_name
      remove :name
      remove :tcgdex_id
    end

    drop constraint(
           :single_valuation_snapshots,
           "single_valuation_snapshots_card_printing_id_fkey"
         )

    alter table(:single_valuation_snapshots) do
      modify :card_printing_id, :uuid
    end

    drop table(:card_printings)

    drop_if_exists index(:single_valuation_snapshots, [
                     :card_printing_id,
                     :policy_version,
                     :fetched_at
                   ])

    drop_if_exists index(:single_valuation_snapshots, [:card_printing_id, :policy_version])

    drop table(:single_valuation_snapshots)
  end
end
