defmodule TcgCheap.Repo.Migrations.CardmarketEvidenceIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(
                     :cardmarket_card_mapping_evidence,
                     [:source_batch_id, :card_printing_id],
                     name: "cm_card_evidence_batch_printing_idx"
                   )

    create unique_index(
             :cardmarket_card_mapping_evidence,
             [:source_batch_id, :expansion_mapping_id, :card_printing_id],
             name: "cm_card_evidence_batch_mapping_printing_idx"
           )
  end

  def down do
    raise "cardmarket evidence identity migration is irreversible: restoring the batch/card unique index would fail when a batch contains evidence for multiple expansion mappings"
  end
end
