defmodule TcgCheap.Repo.Migrations.CardmarketExpansionReviewHardening do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_set_cardmarket_mapping_decisions) do
      add :card_set_version_at, :utc_datetime_usec, null: false
    end

    drop_if_exists constraint(
                     :card_set_cardmarket_mapping_decisions,
                     :card_set_cardmarket_mapping_decisions_invariant
                   )

    alter table(:card_set_cardmarket_mapping_decisions) do
      remove :card_set_version
    end

    create constraint(
             :card_set_cardmarket_mapping_decisions,
             :card_set_cardmarket_mapping_decisions_invariant,
             check: """
               event IN ('approved', 'corrected') AND btrim(reason) <> '' AND char_length(reason) <= 2000 AND btrim(actor_email) <> ''
             """
           )

    drop_if_exists constraint(:card_sets, :card_sets_cardmarket_mapping_invariant)

    create constraint(:card_sets, :card_sets_cardmarket_mapping_invariant,
             check: """
               cardmarket_mapping_status IN ('pending', 'matched') AND ((cardmarket_mapping_status = 'pending' AND cardmarket_expansion_id IS NULL AND cardmarket_mapping_authority IS NULL AND cardmarket_mapping_reason IS NULL) OR (cardmarket_mapping_status = 'matched' AND cardmarket_expansion_id > 0 AND cardmarket_mapping_authority = 'administrator' AND cardmarket_mapping_reason IS NOT NULL AND btrim(cardmarket_mapping_reason) <> ''))
             """
           )
  end

  def down do
    raise "Irreversible migration: card_set_version_at cannot reconstruct the removed integer card_set_version, and adding a NOT NULL column without data is unsafe."
  end
end
