defmodule TcgCheap.Repo.Migrations.SealedBuyingGuideHistoryRevisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sealed_buying_guide_snapshots) do
      add :source_history_fingerprint, :text, null: false
    end

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_history_fingerprint_invariant,
             check: """
               source_history_fingerprint ~ '^[0-9a-f]{64}$'
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_history_fingerprint_invariant
                   )

    alter table(:sealed_buying_guide_snapshots) do
      remove :source_history_fingerprint
    end
  end
end
