defmodule TcgCheap.Repo.Migrations.AddTcgdexCatalogueImport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:card_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tcgdex_id, :text, null: false
      add :name, :text, null: false
      add :series_id, :text
      add :series_name, :text
      add :release_date, :date
      add :logo_url, :text
      add :symbol_url, :text
      add :official_count, :bigint
      add :total_count, :bigint
      add :standard_legal, :boolean
      add :expanded_legal, :boolean
      add :source_payload, :map
      add :last_synced_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:card_sets, [:tcgdex_id], name: "card_sets_unique_tcgdex_id_index")

    alter table(:card_printings) do
      add :image_url, :text
      add :rarity, :text
      add :category, :text
      add :illustrator, :text
      add :regulation_mark, :text
      add :standard_legal, :boolean
      add :expanded_legal, :boolean
      add :variant_data, :map
      add :source_updated_at, :utc_datetime_usec
      add :mapping_updated_at, :utc_datetime_usec
      add :source_payload, :map
      add :last_synced_at, :utc_datetime_usec
      add :cardmarket_product_id, :bigint
      add :mapping_status, :text, null: false, default: "pending"
      add :mapping_review_reason, :text

      add :card_set_id,
          references(:card_sets,
            column: :id,
            name: "card_printings_card_set_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:card_printings, [:card_set_id])

    create constraint(:card_printings, :card_printings_mapping_invariant,
             check: """
               mapping_status IN ('pending', 'matched', 'unmatched', 'review') AND ((mapping_status IN ('pending', 'unmatched') AND cardmarket_product_id IS NULL AND mapping_review_reason IS NULL) OR (mapping_status = 'matched' AND cardmarket_product_id IS NOT NULL AND cardmarket_product_id > 0 AND mapping_review_reason IS NULL) OR (mapping_status = 'review' AND cardmarket_product_id IS NULL AND mapping_review_reason IS NOT NULL AND btrim(mapping_review_reason) <> ''))
             """
           )

    create constraint(:card_sets, :card_sets_counts_invariant,
             check: """
               (official_count IS NULL OR official_count >= 0) AND (total_count IS NULL OR total_count >= 0) AND (official_count IS NULL OR total_count IS NULL OR official_count <= total_count)
             """
           )
  end

  def down do
    drop_if_exists constraint(:card_sets, :card_sets_counts_invariant)

    drop_if_exists constraint(:card_printings, :card_printings_mapping_invariant)

    drop_if_exists index(:card_printings, [:card_set_id])

    drop constraint(:card_printings, "card_printings_card_set_id_fkey")

    alter table(:card_printings) do
      remove :card_set_id
      remove :mapping_review_reason
      remove :mapping_status
      remove :cardmarket_product_id
      remove :last_synced_at
      remove :source_payload
      remove :mapping_updated_at
      remove :source_updated_at
      remove :variant_data
      remove :expanded_legal
      remove :standard_legal
      remove :regulation_mark
      remove :illustrator
      remove :category
      remove :rarity
      remove :image_url
    end

    drop_if_exists unique_index(:card_sets, [:tcgdex_id],
                     name: "card_sets_unique_tcgdex_id_index"
                   )

    drop table(:card_sets)
  end
end
