defmodule TcgCheap.Repo.Migrations.HomepageSealedMovers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(
             :sealed_daily_aggregates,
             [:sealed_product_id, :calculation_version, :aggregate_date, :calculated_at, :id],
             name: "sealed_daily_aggregates_homepage_window_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(
                     :sealed_daily_aggregates,
                     [
                       :sealed_product_id,
                       :calculation_version,
                       :aggregate_date,
                       :calculated_at,
                       :id
                     ],
                     name: "sealed_daily_aggregates_homepage_window_index"
                   )
  end
end
