defmodule TcgCheap.Repo.Migrations.HardenSealedDailyAggregates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_state_invariant)

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_state_invariant,
             check: """
               (status = 'ready' AND limited_reason IS NULL AND benchmark_pln IS NOT NULL AND typical_low_pln IS NOT NULL AND typical_high_pln IS NOT NULL AND fresh_regular_retailer_count >= 5 AND latest_nonfuture_checked_at IS NOT NULL) OR (status = 'limited' AND limited_reason IN ('no_fresh_current_offers', 'too_few_regular_retailers', 'insufficient_inliers') AND benchmark_pln IS NULL AND typical_low_pln IS NULL AND typical_high_pln IS NULL)
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_reason_invariant,
             check: """
               status = 'ready' OR (limited_reason = 'no_fresh_current_offers' AND fresh_regular_retailer_count = 0 AND fresh_lgs_count = 0) OR (limited_reason = 'too_few_regular_retailers' AND fresh_regular_retailer_count < 5 AND fresh_regular_retailer_count + fresh_lgs_count > 0) OR (limited_reason = 'insufficient_inliers' AND fresh_regular_retailer_count >= 5)
             """
           )

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_checked_at_invariant,
             check: """
               latest_nonfuture_checked_at IS NULL OR latest_nonfuture_checked_at <= calculated_at
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :sealed_daily_aggregates,
                     :sealed_daily_aggregates_checked_at_invariant
                   )

    drop_if_exists constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_reason_invariant)

    drop_if_exists constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_state_invariant)

    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_state_invariant,
             check: """
               (status = 'ready' AND limited_reason IS NULL AND benchmark_pln IS NOT NULL AND typical_low_pln IS NOT NULL AND typical_high_pln IS NOT NULL) OR (status = 'limited' AND limited_reason IN ('no_fresh_current_offers', 'too_few_regular_retailers', 'insufficient_inliers') AND benchmark_pln IS NULL AND typical_low_pln IS NULL AND typical_high_pln IS NULL)
             """
           )
  end
end
