defmodule TcgCheap.Repo.Migrations.HardenCardmarketBulkPipeline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cardmarket_bulk_batches) do
      add :status, :text, null: false, default: "staged"
      add :failure_summary, :text
      modify :completed_at, :utc_datetime_usec, null: true
    end

    # Existing completed imports predate lifecycle states and are trusted legacy
    # evidence; preserve their readiness semantics while introducing the state.
    execute "UPDATE cardmarket_bulk_batches SET status = 'succeeded' WHERE completed_at IS NOT NULL"

    drop_if_exists constraint(
                     :cardmarket_bulk_batches,
                     :cardmarket_bulk_batches_timestamps_coherent
                   )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_status_valid,
             check: """
               status IN ('staged', 'succeeded', 'failed')
             """
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_failure_summary_bounded,
             check: """
                failure_summary IS NULL OR (btrim(failure_summary) <> '' AND octet_length(failure_summary) <= 160)
             """
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_lifecycle_coherent,
             check: """
               (status = 'staged' AND completed_at IS NULL AND failure_summary IS NULL) OR (status = 'succeeded' AND completed_at IS NOT NULL AND failure_summary IS NULL) OR (status = 'failed' AND completed_at IS NOT NULL AND failure_summary IS NOT NULL)
             """
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_timestamps_coherent,
             check: """
               fetched_at >= product_created_at AND fetched_at >= price_created_at AND (completed_at IS NULL OR completed_at >= fetched_at)
             """
           )
  end

  def down do
    raise "Irreversible migration: staged and failed Cardmarket bulk batches have nullable completed_at values, so the old NOT NULL lifecycle schema cannot be restored safely."
  end
end
