defmodule TcgCheap.Repo.Migrations.AddSinglesCollectionScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_printings) do
      add :collection_scopes, {:array, :text}, null: false, default: []
      add :collection_scope_source, :text
      add :collection_scoped_at, :utc_datetime_usec
      add :collection_expires_on, :date
    end

    create constraint(:card_printings, :card_printings_collection_scope_invariant,
             check: """
                ((collection_scopes = '{}' AND collection_scope_source IS NULL AND collection_scoped_at IS NULL AND collection_expires_on IS NULL) OR (collection_scopes <> '{}' AND collection_scope_source IS NOT NULL AND collection_scoped_at IS NOT NULL)) AND (collection_expires_on IS NULL OR collection_scoped_at IS NULL OR collection_expires_on >= (collection_scoped_at AT TIME ZONE 'UTC')::date)
             """
           )

    create constraint(:card_printings, :card_printings_collection_scope_values,
             check: """
                collection_scopes <@ ARRAY['pitch_black_full', 'rolling_ir_sir', 'curated_playable', 'legacy_local']::text[]
             """
           )

    create constraint(:card_printings, :card_printings_collection_scope_source_values,
             check: """
                collection_scope_source IS NULL OR collection_scope_source IN ('system', 'administrator', 'legacy')
             """
           )
  end

  def down do
    drop_if_exists constraint(:card_printings, :card_printings_collection_scope_source_values)

    drop_if_exists constraint(:card_printings, :card_printings_collection_scope_values)

    drop_if_exists constraint(:card_printings, :card_printings_collection_scope_invariant)

    alter table(:card_printings) do
      remove :collection_expires_on
      remove :collection_scoped_at
      remove :collection_scope_source
      remove :collection_scopes
    end
  end
end
