defmodule TcgCheap.Repo.Migrations.CardmarketExpansionReview do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:card_set_cardmarket_mapping_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event, :text, null: false
      add :from_expansion_id, :bigint
      add :to_expansion_id, :bigint, null: false
      add :reason, :text, null: false
      add :card_set_version, :bigint, null: false
      add :actor_email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :card_set_id,
          references(:card_sets,
            column: :id,
            name: "card_set_cardmarket_mapping_decisions_card_set_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :source_mapping_id,
          references(:cardmarket_expansion_mappings,
            column: :id,
            name: "card_set_cardmarket_mapping_decisions_source_mapping_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :source_batch_id,
          references(:cardmarket_bulk_batches,
            column: :id,
            name: "card_set_cardmarket_mapping_decisions_source_batch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :actor_id,
          references(:admins,
            column: :id,
            name: "card_set_cardmarket_mapping_decisions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create constraint(
             :card_set_cardmarket_mapping_decisions,
             :card_set_cardmarket_mapping_decisions_invariant,
             check: """
               event IN ('approved', 'corrected') AND btrim(reason) <> '' AND char_length(reason) <= 2000 AND btrim(actor_email) <> '' AND card_set_version > 0
             """
           )

    create constraint(
             :card_set_cardmarket_mapping_decisions,
             :card_set_cardmarket_mapping_decisions_expansions_positive,
             check: """
               (from_expansion_id IS NULL OR from_expansion_id > 0) AND to_expansion_id > 0
             """
           )

    create index(:card_set_cardmarket_mapping_decisions, [:card_set_id, :inserted_at, :id])

    create index(:card_set_cardmarket_mapping_decisions, [:source_batch_id])

    alter table(:card_sets) do
      add :cardmarket_expansion_id, :bigint
      add :cardmarket_mapping_status, :text, null: false, default: "pending"
      add :cardmarket_mapping_authority, :text
      add :cardmarket_mapping_evidence_at, :utc_datetime_usec
      add :cardmarket_mapping_reason, :text
    end

    create constraint(:card_sets, :card_sets_cardmarket_mapping_invariant,
             check: """
               cardmarket_mapping_status IN ('pending', 'matched') AND ((cardmarket_mapping_status = 'pending' AND cardmarket_expansion_id IS NULL AND cardmarket_mapping_authority IS NULL AND cardmarket_mapping_reason IS NULL) OR (cardmarket_mapping_status = 'matched' AND cardmarket_expansion_id > 0 AND cardmarket_mapping_authority IN ('system', 'administrator') AND cardmarket_mapping_reason IS NOT NULL AND btrim(cardmarket_mapping_reason) <> ''))
             """
           )

    create index(:card_sets, [:cardmarket_expansion_id],
             unique: true,
             where: "cardmarket_mapping_authority = 'administrator'"
           )
  end

  def down do
    drop_if_exists index(:card_sets, [:cardmarket_expansion_id])

    drop_if_exists constraint(:card_sets, :card_sets_cardmarket_mapping_invariant)

    alter table(:card_sets) do
      remove :cardmarket_mapping_reason
      remove :cardmarket_mapping_evidence_at
      remove :cardmarket_mapping_authority
      remove :cardmarket_mapping_status
      remove :cardmarket_expansion_id
    end

    drop_if_exists index(:card_set_cardmarket_mapping_decisions, [:source_batch_id])

    drop_if_exists index(:card_set_cardmarket_mapping_decisions, [:card_set_id, :inserted_at, :id])

    drop_if_exists constraint(
                     :card_set_cardmarket_mapping_decisions,
                     :card_set_cardmarket_mapping_decisions_expansions_positive
                   )

    drop_if_exists constraint(
                     :card_set_cardmarket_mapping_decisions,
                     :card_set_cardmarket_mapping_decisions_invariant
                   )

    drop constraint(
           :card_set_cardmarket_mapping_decisions,
           "card_set_cardmarket_mapping_decisions_actor_id_fkey"
         )

    drop constraint(
           :card_set_cardmarket_mapping_decisions,
           "card_set_cardmarket_mapping_decisions_source_batch_id_fkey"
         )

    drop constraint(
           :card_set_cardmarket_mapping_decisions,
           "card_set_cardmarket_mapping_decisions_source_mapping_id_fkey"
         )

    drop constraint(
           :card_set_cardmarket_mapping_decisions,
           "card_set_cardmarket_mapping_decisions_card_set_id_fkey"
         )

    drop table(:card_set_cardmarket_mapping_decisions)
  end
end
