defmodule TcgCheap.Repo.Migrations.EnrichSealedProductDetails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:retailer_listings) do
      add :image_url, :text
    end

    create constraint(:retailer_listings, :retailer_listings_image_url_invariant,
             check: """
                image_url IS NULL OR image_url ~* '^https://((assets\\.tcgdex\\.net|assets\\.pokemon\\.com|www\\.pokemon\\.com|mcdn\\.pokemon\\.com)|([a-z0-9-]+\\.)*(lootquest\\.pl|cardzhouse\\.pl|boosterpoint\\.pl|pokebooster\\.pl))(/|[/?#].*)?$'
             """
           )

    alter table(:sealed_products) do
      add :description, :text
      add :contents, {:array, :text}, null: false, default: []
      add :pack_count, :bigint
      add :cards_per_pack, :bigint
      add :official_url, :text
      add :details_source, :text
      add :details_source_url, :text
      add :official_price_amount, :decimal
      add :official_price_currency, :text
      add :official_price_source, :text
      add :official_price_source_url, :text
      add :image_source, :text
      add :image_source_url, :text
    end

    create constraint(:sealed_products, :sealed_products_official_price_invariant,
             check: """
               ((official_price_amount IS NULL AND official_price_currency IS NULL AND official_price_source IS NULL AND official_price_source_url IS NULL) OR (official_price_amount IS NOT NULL AND official_price_currency IS NOT NULL AND official_price_source IS NOT NULL AND official_price_source_url IS NOT NULL AND official_price_amount > 0 AND official_price_amount <> 'NaN'::numeric AND official_price_amount <> 'Infinity'::numeric AND official_price_amount <> '-Infinity'::numeric AND official_price_currency IN ('PLN','USD','EUR') AND btrim(official_price_source) <> '' AND official_price_source_url ~ '^https://[^/@/?#[:space:]]+(/|[/?#].*)?$'))
             """
           )

    create constraint(:sealed_products, :sealed_products_image_provenance_invariant,
             check: """
               ((image_url IS NULL AND image_source IS NULL AND image_source_url IS NULL) OR (image_url IS NOT NULL AND image_source IS NULL AND image_source_url IS NULL) OR (image_url IS NOT NULL AND image_source IS NOT NULL AND image_source_url IS NOT NULL AND image_url ~* '^https://((assets\\.tcgdex\\.net|assets\\.pokemon\\.com|www\\.pokemon\\.com|mcdn\\.pokemon\\.com)|([a-z0-9-]+\\.)*(lootquest\\.pl|cardzhouse\\.pl|boosterpoint\\.pl|pokebooster\\.pl))(/|[/?#].*)?$' AND btrim(image_source) <> '' AND image_source_url ~ '^https://[^/@/?#[:space:]]+(/|[/?#].*)?$'))
             """
           )

    create constraint(:sealed_products, :sealed_products_details_provenance_invariant,
             check: """
               ((description IS NULL AND contents = '{}'::text[] AND pack_count IS NULL AND cards_per_pack IS NULL AND official_url IS NULL AND details_source IS NULL AND details_source_url IS NULL) OR (details_source IS NOT NULL AND details_source_url IS NOT NULL AND btrim(details_source) <> '' AND details_source_url ~ '^https://[^/@/?#[:space:]]+(/|[/?#].*)?$'))
             """
           )
  end

  def down do
    drop_if_exists constraint(:sealed_products, :sealed_products_details_provenance_invariant)

    drop_if_exists constraint(:sealed_products, :sealed_products_image_provenance_invariant)

    drop_if_exists constraint(:sealed_products, :sealed_products_official_price_invariant)

    alter table(:sealed_products) do
      remove :image_source_url
      remove :image_source
      remove :official_price_source_url
      remove :official_price_source
      remove :official_price_currency
      remove :official_price_amount
      remove :details_source_url
      remove :details_source
      remove :official_url
      remove :cards_per_pack
      remove :pack_count
      remove :contents
      remove :description
    end

    drop_if_exists constraint(:retailer_listings, :retailer_listings_image_url_invariant)

    alter table(:retailer_listings) do
      remove :image_url
    end
  end
end
