defmodule TcgCheap.Repo.Migrations.CardPrintingMappingTransition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_transition_invariant
                   )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_transition_invariant,
             check: """
               (event = 'imported' AND from_status IS NULL AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'baseline' AND from_status IS NULL AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'provider_updated' AND from_status IN ('pending', 'matched', 'unmatched', 'review') AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'corrected' AND from_status IN ('pending', 'matched', 'unmatched', 'review') AND to_status = 'matched') OR (event = 'reopened' AND from_status IN ('matched', 'unmatched') AND to_status = 'review')
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_transition_invariant
                   )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_transition_invariant,
             check: """
               (event = 'imported' AND from_status IS NULL) OR (event = 'baseline' AND from_status IS NULL) OR (event = 'provider_updated' AND from_status IS NOT NULL) OR (event = 'corrected' AND to_status = 'matched' AND from_status IS NOT NULL) OR (event = 'reopened' AND from_status IN ('matched', 'unmatched') AND to_status = 'review')
             """
           )
  end
end
