defmodule TcgCheap.Repo.Migrations.CardPrintingMappingConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_transition_invariant
                   )

    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_state_invariant
                   )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_transition_invariant,
             check: """
               ((from_status = 'matched' AND from_cardmarket_product_id IS NOT NULL AND from_cardmarket_product_id > 0) OR (from_status IS NULL OR from_status IN ('pending', 'unmatched', 'review')) AND from_cardmarket_product_id IS NULL) AND ((event = 'imported' AND from_status IS NULL AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'baseline' AND from_status IS NULL AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'provider_updated' AND from_status IN ('pending', 'matched', 'unmatched', 'review') AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'corrected' AND from_status IN ('pending', 'matched', 'unmatched', 'review') AND to_status = 'matched') OR (event = 'reopened' AND from_status IN ('matched', 'unmatched') AND to_status = 'review'))
             """
           )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_state_invariant,
             check: """
               ((to_status = 'matched' AND cardmarket_product_id IS NOT NULL AND cardmarket_product_id > 0 AND (reason IS NULL OR (event = 'corrected' AND btrim(reason) <> ''))) OR (to_status IN ('pending', 'unmatched') AND cardmarket_product_id IS NULL AND reason IS NULL) OR (to_status = 'review' AND cardmarket_product_id IS NULL AND reason IS NOT NULL AND btrim(reason) <> '')) AND char_length(coalesce(reason, '')) <= 2000
             """
           )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_event_authority_actor_invariant,
             check: """
               (event IN ('imported', 'provider_updated', 'baseline') AND mapping_authority = 'provider' AND actor_type = 'system') OR (event IN ('corrected', 'reopened') AND mapping_authority = 'administrator' AND actor_type = 'administrator')
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_event_authority_actor_invariant
                   )

    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_state_invariant
                   )

    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_transition_invariant
                   )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_state_invariant,
             check: """
               ((to_status = 'matched' AND cardmarket_product_id IS NOT NULL AND cardmarket_product_id > 0 AND (reason IS NULL OR (event = 'corrected' AND btrim(reason) <> ''))) OR (to_status IN ('pending', 'unmatched') AND cardmarket_product_id IS NULL AND reason IS NULL) OR (to_status = 'review' AND cardmarket_product_id IS NULL AND reason IS NOT NULL AND btrim(reason) <> ''))
             """
           )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_transition_invariant,
             check: """
               (event = 'imported' AND from_status IS NULL AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'baseline' AND from_status IS NULL AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'provider_updated' AND from_status IN ('pending', 'matched', 'unmatched', 'review') AND to_status IN ('pending', 'matched', 'unmatched', 'review')) OR (event = 'corrected' AND from_status IN ('pending', 'matched', 'unmatched', 'review') AND to_status = 'matched') OR (event = 'reopened' AND from_status IN ('matched', 'unmatched') AND to_status = 'review')
             """
           )
  end
end
