defmodule TcgCheap.Repo.Migrations.AddNormalizedCardPrintingSearch1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:card_printings, ["search_tcgdex_id gin_trgm_ops"],
             name: "card_printings_search_tcgdex_id_trgm_index",
             concurrently: true,
             using: "gin"
           )

    create index(:card_printings, ["search_collector_number gin_trgm_ops"],
             name: "card_printings_search_collector_number_trgm_index",
             concurrently: true,
             using: "gin"
           )

    create index(:card_printings, ["search_set_name gin_trgm_ops"],
             name: "card_printings_search_set_name_trgm_index",
             concurrently: true,
             using: "gin"
           )

    create index(:card_printings, ["search_name gin_trgm_ops"],
             name: "card_printings_search_name_trgm_index",
             concurrently: true,
             using: "gin"
           )
  end

  def down do
    drop_if_exists index(:card_printings, ["search_name gin_trgm_ops"],
                     name: "card_printings_search_name_trgm_index"
                   )

    drop_if_exists index(:card_printings, ["search_set_name gin_trgm_ops"],
                     name: "card_printings_search_set_name_trgm_index"
                   )

    drop_if_exists index(:card_printings, ["search_collector_number gin_trgm_ops"],
                     name: "card_printings_search_collector_number_trgm_index"
                   )

    drop_if_exists index(:card_printings, ["search_tcgdex_id gin_trgm_ops"],
                     name: "card_printings_search_tcgdex_id_trgm_index"
                   )
  end
end
