defmodule TcgCheap.Repo.Migrations.CardmarketBulkCrosswalk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cardmarket_card_mapping_evidence, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :cardmarket_product_id, :bigint
      add :normalized_card_name, :text, null: false
      add :evidence, :map, null: false, default: %{}
      add :review_reason, :text
      add :authority, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_batch_id,
          references(:cardmarket_bulk_batches,
            column: :id,
            name: "cardmarket_card_mapping_evidence_source_batch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :expansion_mapping_id, :uuid, null: false

      add :card_printing_id,
          references(:card_printings,
            column: :id,
            name: "cardmarket_card_mapping_evidence_card_printing_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:cardmarket_card_mapping_evidence, [:source_batch_id, :card_printing_id],
             name: "cm_card_evidence_batch_printing_idx"
           )

    create index(:cardmarket_card_mapping_evidence, [:source_batch_id])

    create index(:cardmarket_card_mapping_evidence, [:card_printing_id])

    create table(:cardmarket_expansion_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cardmarket_card_mapping_evidence) do
      modify :expansion_mapping_id,
             references(:cardmarket_expansion_mappings,
               column: :id,
               name: "cardmarket_card_mapping_evidence_expansion_mapping_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(
             :cardmarket_card_mapping_evidence,
             :cardmarket_card_mapping_evidence_invariant,
             check: """
               ((decision IN ('anchor','auto_matched') AND cardmarket_product_id IS NOT NULL AND cardmarket_product_id > 0 AND review_reason IS NULL) OR (decision = 'review' AND cardmarket_product_id IS NULL AND review_reason IS NOT NULL AND btrim(review_reason) <> '') OR (decision = 'unmatched' AND cardmarket_product_id IS NULL AND review_reason IS NULL)) AND char_length(coalesce(review_reason, '')) <= 2000
             """
           )

    create constraint(
             :cardmarket_card_mapping_evidence,
             :cardmarket_card_mapping_evidence_authority_invariant,
             check: """
               authority IN ('system','administrator')
             """
           )

    create constraint(
             :cardmarket_card_mapping_evidence,
             :cardmarket_card_mapping_evidence_evidence_present,
             check: """
               evidence <> '{}'::jsonb
             """
           )

    alter table(:cardmarket_expansion_mappings) do
      add :expansion_id, :bigint, null: false
      add :status, :text, null: false
      add :authority, :text, null: false
      add :anchor_count, :bigint, null: false
      add :evidence, :map, null: false, default: %{}
      add :review_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_batch_id,
          references(:cardmarket_bulk_batches,
            column: :id,
            name: "cardmarket_expansion_mappings_source_batch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :card_set_id,
          references(:card_sets,
            column: :id,
            name: "cardmarket_expansion_mappings_card_set_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(
             :cardmarket_expansion_mappings,
             [:source_batch_id, :card_set_id, :expansion_id],
             name: "cm_expansion_map_batch_set_expansion_idx"
           )

    create constraint(:cardmarket_expansion_mappings, :cardmarket_expansion_mappings_invariant,
             check: """
               expansion_id > 0 AND anchor_count > 0 AND ((status = 'approved' AND review_reason IS NULL) OR (status = 'review' AND review_reason IS NOT NULL AND btrim(review_reason) <> '')) AND char_length(coalesce(review_reason, '')) <= 2000
             """
           )

    create constraint(
             :cardmarket_expansion_mappings,
             :cardmarket_expansion_mappings_authority_invariant,
             check: """
               authority IN ('system', 'administrator')
             """
           )

    create constraint(
             :cardmarket_expansion_mappings,
             :cardmarket_expansion_mappings_evidence_present,
             check: """
               evidence <> '{}'::jsonb
             """
           )

    create index(:cardmarket_expansion_mappings, [:source_batch_id])

    create index(:cardmarket_expansion_mappings, [:card_set_id])
  end

  def down do
    drop_if_exists index(:cardmarket_expansion_mappings, [:card_set_id])

    drop_if_exists index(:cardmarket_expansion_mappings, [:source_batch_id])

    drop_if_exists constraint(
                     :cardmarket_expansion_mappings,
                     :cardmarket_expansion_mappings_evidence_present
                   )

    drop_if_exists constraint(
                     :cardmarket_expansion_mappings,
                     :cardmarket_expansion_mappings_authority_invariant
                   )

    drop_if_exists constraint(
                     :cardmarket_expansion_mappings,
                     :cardmarket_expansion_mappings_invariant
                   )

    drop constraint(
           :cardmarket_expansion_mappings,
           "cardmarket_expansion_mappings_card_set_id_fkey"
         )

    drop constraint(
           :cardmarket_expansion_mappings,
           "cardmarket_expansion_mappings_source_batch_id_fkey"
         )

    drop_if_exists unique_index(
                     :cardmarket_expansion_mappings,
                     [:source_batch_id, :card_set_id, :expansion_id],
                     name: "cm_expansion_map_batch_set_expansion_idx"
                   )

    alter table(:cardmarket_expansion_mappings) do
      remove :card_set_id
      remove :source_batch_id
      remove :inserted_at
      remove :review_reason
      remove :evidence
      remove :anchor_count
      remove :authority
      remove :status
      remove :expansion_id
    end

    drop_if_exists constraint(
                     :cardmarket_card_mapping_evidence,
                     :cardmarket_card_mapping_evidence_evidence_present
                   )

    drop_if_exists constraint(
                     :cardmarket_card_mapping_evidence,
                     :cardmarket_card_mapping_evidence_authority_invariant
                   )

    drop_if_exists constraint(
                     :cardmarket_card_mapping_evidence,
                     :cardmarket_card_mapping_evidence_invariant
                   )

    drop constraint(
           :cardmarket_card_mapping_evidence,
           "cardmarket_card_mapping_evidence_card_printing_id_fkey"
         )

    drop constraint(
           :cardmarket_card_mapping_evidence,
           "cardmarket_card_mapping_evidence_expansion_mapping_id_fkey"
         )

    drop constraint(
           :cardmarket_card_mapping_evidence,
           "cardmarket_card_mapping_evidence_source_batch_id_fkey"
         )

    alter table(:cardmarket_card_mapping_evidence) do
      modify :expansion_mapping_id, :uuid
    end

    drop table(:cardmarket_expansion_mappings)

    drop_if_exists index(:cardmarket_card_mapping_evidence, [:card_printing_id])

    drop_if_exists index(:cardmarket_card_mapping_evidence, [:source_batch_id])

    drop_if_exists unique_index(
                     :cardmarket_card_mapping_evidence,
                     [:source_batch_id, :card_printing_id],
                     name: "cm_card_evidence_batch_printing_idx"
                   )

    drop table(:cardmarket_card_mapping_evidence)
  end
end
