defmodule TcgCheap.Repo.Migrations.EnforceSealedAggregateCoverage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:sealed_daily_aggregates, :sealed_daily_aggregates_coverage_invariant,
             check: """
               unique_source_retailer_count >= fresh_regular_retailer_count + fresh_lgs_count
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :sealed_daily_aggregates,
                     :sealed_daily_aggregates_coverage_invariant
                   )
  end
end
