defmodule TcgCheap.Repo.Migrations.AddCatalogueEnrichmentOperation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_operation_invariant)

    create constraint(:acquisition_runs, :acquisition_runs_operation_invariant,
             check: """
               operation IN ('single_valuation','exchange_rate','sealed_retailer_refresh','card_catalogue_sync','card_catalogue_enrichment')
             """
           )
  end

  def down do
    execute("DELETE FROM acquisition_runs WHERE operation = 'card_catalogue_enrichment'")

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_operation_invariant)

    create constraint(:acquisition_runs, :acquisition_runs_operation_invariant,
             check: """
               operation IN ('single_valuation','exchange_rate','sealed_retailer_refresh','card_catalogue_sync')
             """
           )
  end
end
