defmodule TcgCheap.Repo.Migrations.RemoveLegacySinglesPricing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_printings) do
      remove :pricing_checked_at
    end
  end

  def down do
    alter table(:card_printings) do
      add :pricing_checked_at, :utc_datetime_usec
    end
  end
end
