defmodule TcgCheap.Repo.Migrations.HardenCardmarketBulkPipelineConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(
                     :cardmarket_bulk_batches,
                     :cardmarket_bulk_batches_failure_summary_bounded
                   )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_failure_summary_bounded,
             check: """
               failure_summary IS NULL OR (btrim(failure_summary) <> '' AND octet_length(failure_summary) <= 160)
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :cardmarket_bulk_batches,
                     :cardmarket_bulk_batches_failure_summary_bounded
                   )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_failure_summary_bounded,
             check: """
               failure_summary IS NULL OR btrim(failure_summary) <> ''
             """
           )
  end
end
