defmodule TcgCheap.Repo.Migrations.AcquisitionObservabilityHardening do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:acquisition_runs, [:started_at, :id])

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_lifecycle_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_status_invariant)

    create constraint(:acquisition_runs, :acquisition_runs_lifecycle_invariant,
             check: """
               (status = 'running' AND finished_at IS NULL AND failure_category IS NULL) OR (status = 'succeeded' AND finished_at IS NOT NULL AND failure_category IS NULL) OR (status IN ('retryable_failure','failed','cancelled') AND finished_at IS NOT NULL AND failure_category IS NOT NULL)
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_status_invariant,
             check: """
               status IN ('running','succeeded','retryable_failure','failed','cancelled')
             """
           )

    drop_if_exists constraint(:acquisition_source_health, :source_health_state_invariant)

    drop_if_exists constraint(:acquisition_source_health, :source_health_status_invariant)

    create constraint(:acquisition_source_health, :source_health_state_invariant,
             check: """
               last_started_at IS NOT NULL AND ((last_status IS NULL AND last_succeeded_at IS NULL AND last_failed_at IS NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status = 'succeeded' AND last_succeeded_at IS NOT NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status IN ('retryable_failure','failed','cancelled') AND last_failed_at IS NOT NULL AND last_failure_category IS NOT NULL AND consecutive_failures > 0))
             """
           )

    create constraint(:acquisition_source_health, :source_health_status_invariant,
             check: """
               last_status IS NULL OR last_status IN ('succeeded','retryable_failure','failed','cancelled')
             """
           )
  end

  def down do
    drop_if_exists constraint(:acquisition_source_health, :source_health_status_invariant)

    drop_if_exists constraint(:acquisition_source_health, :source_health_state_invariant)

    execute(
      "UPDATE acquisition_source_health SET last_status = 'retryable_failure' WHERE last_status = 'failed'"
    )

    create constraint(:acquisition_source_health, :source_health_status_invariant,
             check: """
               last_status IS NULL OR last_status IN ('succeeded','retryable_failure','cancelled')
             """
           )

    create constraint(:acquisition_source_health, :source_health_state_invariant,
             check: """
               last_started_at IS NOT NULL AND ((last_status IS NULL AND last_succeeded_at IS NULL AND last_failed_at IS NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status = 'succeeded' AND last_succeeded_at IS NOT NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status IN ('retryable_failure','cancelled') AND last_failed_at IS NOT NULL AND last_failure_category IS NOT NULL AND consecutive_failures > 0))
             """
           )

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_status_invariant)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_lifecycle_invariant)

    execute("UPDATE acquisition_runs SET status = 'retryable_failure' WHERE status = 'failed'")

    create constraint(:acquisition_runs, :acquisition_runs_status_invariant,
             check: """
               status IN ('running','succeeded','retryable_failure','cancelled')
             """
           )

    create constraint(:acquisition_runs, :acquisition_runs_lifecycle_invariant,
             check: """
               (status = 'running' AND finished_at IS NULL AND failure_category IS NULL) OR (status = 'succeeded' AND finished_at IS NOT NULL AND failure_category IS NULL) OR (status IN ('retryable_failure','cancelled') AND finished_at IS NOT NULL AND failure_category IS NOT NULL)
             """
           )

    drop_if_exists index(:acquisition_runs, [:started_at, :id])
  end
end
