defmodule TcgCheap.Repo.Migrations.CataloguePartialIssueStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:import_issues, :import_issues_kind_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_code_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_kind_code_invariant)

    create constraint(:import_issues, :import_issues_kind_invariant,
             check: """
               issue_kind IN ('unmatched','ambiguous','partial','malformed','failed')
             """
           )

    create constraint(:import_issues, :import_issues_code_invariant,
             check: """
               issue_code IN ('partial_coverage','malformed_response','budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown')
             """
           )

    create constraint(:import_issues, :import_issues_kind_code_invariant,
             check: """
               (issue_kind IN ('unmatched','ambiguous') AND issue_code = 'provider_response') OR (issue_kind = 'partial' AND issue_code = 'partial_coverage') OR (issue_kind = 'malformed' AND issue_code = 'malformed_response') OR (issue_kind = 'failed' AND issue_code IN ('budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown'))
             """
           )
  end

  def down do
    drop_if_exists constraint(:import_issues, :import_issues_kind_code_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_code_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_kind_invariant)

    execute """
    WITH duplicate_rows AS (
      SELECT partial.id AS partial_id, malformed.id AS malformed_id
      FROM import_issues AS partial
      JOIN import_issues AS malformed
        ON malformed.provider_key = partial.provider_key
       AND malformed.operation = partial.operation
       AND malformed.stage = partial.stage
       AND malformed.target_type = partial.target_type
       AND malformed.target_key = partial.target_key
       AND malformed.issue_kind = 'malformed'
       AND malformed.issue_code = 'malformed_response'
      WHERE partial.issue_kind = 'partial'
        AND partial.issue_code = 'partial_coverage'
    ), merged AS (
      UPDATE import_issues AS malformed
      SET first_seen_at = LEAST(malformed.first_seen_at, partial.first_seen_at),
          last_seen_at = GREATEST(malformed.last_seen_at, partial.last_seen_at),
          resolved_at = CASE
            WHEN malformed.resolved_at IS NULL OR partial.resolved_at IS NULL THEN NULL
            ELSE GREATEST(malformed.resolved_at, partial.resolved_at)
          END,
          updated_at = GREATEST(malformed.updated_at, partial.updated_at)
      FROM duplicate_rows AS duplicate
      JOIN import_issues AS partial ON partial.id = duplicate.partial_id
      WHERE malformed.id = duplicate.malformed_id
      RETURNING malformed.id AS malformed_id
    )
    DELETE FROM import_issues AS partial
    USING merged, duplicate_rows
    WHERE partial.id = duplicate_rows.partial_id
      AND duplicate_rows.malformed_id = merged.malformed_id
    """

    execute """
    UPDATE import_issues
    SET issue_kind = 'malformed', issue_code = 'malformed_response'
    WHERE issue_kind = 'partial' OR issue_code = 'partial_coverage'
    """

    create constraint(:import_issues, :import_issues_kind_code_invariant,
             check: """
               (issue_kind IN ('unmatched','ambiguous') AND issue_code = 'provider_response') OR (issue_kind = 'malformed' AND issue_code = 'malformed_response') OR (issue_kind = 'failed' AND issue_code IN ('budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown'))
             """
           )

    create constraint(:import_issues, :import_issues_code_invariant,
             check: """
               issue_code IN ('malformed_response','budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown')
             """
           )

    create constraint(:import_issues, :import_issues_kind_invariant,
             check: """
               issue_kind IN ('unmatched','ambiguous','malformed','failed')
             """
           )
  end
end
