defmodule TcgCheap.Repo.Migrations.ListingProductMappingCorrectionHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:listing_product_mapping_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event, :text, null: false
      add :from_status, :text
      add :to_status, :text, null: false
      add :confidence, :decimal
      add :reason, :text
      add :evidence_method, :text
      add :evidence_gtin, :text
      add :actor_type, :text, null: false
      add :actor_id, :uuid
      add :actor_email, :citext
      add :mapping_updated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mapping_id,
          references(:listing_product_mappings,
            column: :id,
            name: "listing_product_mapping_decisions_mapping_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :candidate_product_id,
          references(:sealed_products,
            column: :id,
            name: "listing_product_mapping_decisions_candidate_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :confirmed_product_id,
          references(:sealed_products,
            column: :id,
            name: "listing_product_mapping_decisions_confirmed_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create index(:listing_product_mapping_decisions, [:mapping_id, :inserted_at, :id])

    create constraint(
             :listing_product_mapping_decisions,
             :listing_product_mapping_decisions_transition_invariant,
             check: """
               (event = 'created' AND from_status IS NULL AND to_status IN ('pending', 'review', 'matched')) OR (event = 'baseline' AND from_status IS NULL AND to_status IN ('pending', 'review', 'matched', 'rejected')) OR (event = 'approved' AND from_status IN ('pending', 'review') AND to_status = 'matched') OR (event = 'rejected' AND from_status IN ('pending', 'review') AND to_status = 'rejected') OR (event = 'reopened' AND from_status IN ('matched', 'rejected') AND to_status = 'review')
             """
           )

    create constraint(
             :listing_product_mapping_decisions,
             :listing_product_mapping_decisions_snapshot_invariant,
             check: """
               (to_status = 'pending' AND candidate_product_id IS NULL AND confirmed_product_id IS NULL AND confidence IS NULL AND reason IS NULL AND evidence_method IS NULL AND evidence_gtin IS NULL) OR (to_status = 'review' AND confirmed_product_id IS NULL AND reason IS NOT NULL AND btrim(reason) <> '' AND (confidence IS NULL OR (confidence > 0 AND confidence <= 1 AND confidence <> 'NaN'::numeric AND confidence <> 'Infinity'::numeric AND confidence <> '-Infinity'::numeric))) OR (to_status = 'matched' AND confirmed_product_id IS NOT NULL AND candidate_product_id IS NULL AND confidence > 0 AND confidence <= 1 AND confidence <> 'NaN'::numeric AND confidence <> 'Infinity'::numeric AND confidence <> '-Infinity'::numeric AND reason IS NULL AND evidence_method IS NOT NULL AND btrim(evidence_method) <> '') OR (to_status = 'rejected' AND candidate_product_id IS NULL AND confirmed_product_id IS NULL AND confidence IS NULL AND reason IS NOT NULL AND btrim(reason) <> '' AND evidence_method IS NULL AND evidence_gtin IS NULL)
             """
           )

    create constraint(
             :listing_product_mapping_decisions,
             :listing_product_mapping_decisions_confidence_finite_invariant,
             check: """
               confidence IS NULL OR (confidence > 0 AND confidence <= 1 AND confidence <> 'NaN'::numeric AND confidence <> 'Infinity'::numeric AND confidence <> '-Infinity'::numeric)
             """
           )

    create constraint(
             :listing_product_mapping_decisions,
             :listing_product_mapping_decisions_actor_invariant,
             check: """
               (actor_type = 'system' AND actor_id IS NULL AND actor_email IS NULL) OR (actor_type = 'administrator' AND actor_id IS NOT NULL AND actor_email IS NOT NULL AND btrim(actor_email) <> '')
             """
           )

    create constraint(
             :listing_product_mapping_decisions,
             :listing_product_mapping_decisions_evidence_invariant,
             check: """
               (evidence_method IS NULL AND evidence_gtin IS NULL) OR (evidence_method IS NOT NULL AND btrim(evidence_method) <> '')
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :listing_product_mapping_decisions,
                     :listing_product_mapping_decisions_evidence_invariant
                   )

    drop_if_exists constraint(
                     :listing_product_mapping_decisions,
                     :listing_product_mapping_decisions_actor_invariant
                   )

    drop_if_exists constraint(
                     :listing_product_mapping_decisions,
                     :listing_product_mapping_decisions_confidence_finite_invariant
                   )

    drop_if_exists constraint(
                     :listing_product_mapping_decisions,
                     :listing_product_mapping_decisions_snapshot_invariant
                   )

    drop_if_exists constraint(
                     :listing_product_mapping_decisions,
                     :listing_product_mapping_decisions_transition_invariant
                   )

    drop constraint(
           :listing_product_mapping_decisions,
           "listing_product_mapping_decisions_mapping_id_fkey"
         )

    drop constraint(
           :listing_product_mapping_decisions,
           "listing_product_mapping_decisions_candidate_product_id_fkey"
         )

    drop constraint(
           :listing_product_mapping_decisions,
           "listing_product_mapping_decisions_confirmed_product_id_fkey"
         )

    drop_if_exists index(:listing_product_mapping_decisions, [:mapping_id, :inserted_at, :id])

    drop table(:listing_product_mapping_decisions)
  end
end
