defmodule TcgCheap.Repo.Migrations.AutomaticProviderCircuitBreaker do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acquisition_source_health) do
      add :circuit_failure_streak, :bigint, null: false, default: 0
    end

    create constraint(
             :acquisition_source_health,
             :source_health_circuit_failure_streak_nonnegative,
             check: """
               circuit_failure_streak >= 0
             """
           )

    alter table(:acquisition_source_health) do
      add :circuit_opened_at, :utc_datetime_usec
    end

    create constraint(:acquisition_source_health, :source_health_circuit_open_invariant,
             check: """
               circuit_opened_at IS NULL OR circuit_failure_streak > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:acquisition_source_health, :source_health_circuit_open_invariant)

    alter table(:acquisition_source_health) do
      remove :circuit_opened_at
    end

    drop_if_exists constraint(
                     :acquisition_source_health,
                     :source_health_circuit_failure_streak_nonnegative
                   )

    alter table(:acquisition_source_health) do
      remove :circuit_failure_streak
    end
  end
end
