defmodule TcgCheap.Repo.Migrations.AcquisitionObservabilityIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:acquisition_runs, [:provider_key, :started_at, :id])
  end

  def down do
    drop_if_exists index(:acquisition_runs, [:provider_key, :started_at, :id])
  end
end
