defmodule TcgCheap.Repo.Migrations.AcquisitionBudgetWindowIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:acquisition_budget_usages, [:window_kind, :window_started_at])
  end

  def down do
    drop_if_exists index(:acquisition_budget_usages, [:window_kind, :window_started_at])
  end
end
