defmodule TcgCheap.Repo.Migrations.EnforceCardPrintingMappingReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_state_invariant
                   )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_state_invariant,
             check: """
               ((to_status = 'matched' AND cardmarket_product_id IS NOT NULL AND cardmarket_product_id > 0 AND ((event = 'corrected' AND reason IS NOT NULL AND btrim(reason) <> '') OR (event <> 'corrected' AND reason IS NULL))) OR (to_status IN ('pending', 'unmatched') AND cardmarket_product_id IS NULL AND reason IS NULL) OR (to_status = 'review' AND cardmarket_product_id IS NULL AND reason IS NOT NULL AND btrim(reason) <> '')) AND char_length(coalesce(reason, '')) <= 2000
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_state_invariant
                   )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_state_invariant,
             check: """
               ((to_status = 'matched' AND cardmarket_product_id IS NOT NULL AND cardmarket_product_id > 0 AND (reason IS NULL OR (event = 'corrected' AND btrim(reason) <> ''))) OR (to_status IN ('pending', 'unmatched') AND cardmarket_product_id IS NULL AND reason IS NULL) OR (to_status = 'review' AND cardmarket_product_id IS NULL AND reason IS NOT NULL AND btrim(reason) <> '')) AND char_length(coalesce(reason, '')) <= 2000
             """
           )
  end
end
