defmodule TcgCheap.Repo.Migrations.BroadenTcgdexCardIdGrammar do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:import_issues, :import_issues_stage_target_invariant)

    create constraint(:import_issues, :import_issues_stage_target_invariant,
             check: """
               (stage IN ('catalogue_fetch','catalogue_validation') AND target_type = 'catalogue' AND target_key = 'tcgdex') OR (stage IN ('set_fetch','set_validation','set_import') AND target_type = 'set' AND octet_length(target_key) BETWEEN 1 AND 128 AND target_key ~ '^[A-Za-z0-9][A-Za-z0-9._-]*$') OR (stage IN ('card_fetch','card_import') AND target_type = 'card' AND octet_length(target_key) BETWEEN 1 AND 128 AND target_key ~ '^[A-Za-z0-9]([A-Za-z0-9._!-]|%[0-9A-Fa-f]{2})*$') OR (stage IN ('retailer_fetch','listing_validation','listing_import') AND target_type = 'retailer' AND target_key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND target_key = lower(target_key))
             """
           )
  end

  def down do
    drop_if_exists constraint(:import_issues, :import_issues_stage_target_invariant)

    create constraint(:import_issues, :import_issues_stage_target_invariant,
             check: """
               (stage IN ('catalogue_fetch','catalogue_validation') AND target_type = 'catalogue' AND target_key = 'tcgdex') OR (stage IN ('set_fetch','set_validation','set_import') AND target_type = 'set') OR (stage IN ('card_fetch','card_import') AND target_type = 'card') OR (stage IN ('retailer_fetch','listing_validation','listing_import') AND target_type = 'retailer' AND target_key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND target_key = lower(target_key))
             """
           )
  end
end
