defmodule TcgCheap.Repo.Migrations.HardenAcquisitionHealth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:acquisition_runs, [:started_at, :id])

    create index(:acquisition_runs, [:started_at, :id], where: "status = 'running'")

    drop_if_exists constraint(:acquisition_source_health, :source_health_state_invariant)

    create constraint(:acquisition_source_health, :source_health_state_invariant,
             check: """
               last_started_at IS NOT NULL AND ((last_status IS NULL AND last_succeeded_at IS NULL AND last_failed_at IS NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status IS NOT NULL AND last_status = 'succeeded' AND last_succeeded_at IS NOT NULL AND (last_failed_at IS NULL OR last_succeeded_at >= last_failed_at) AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status IS NOT NULL AND last_status IN ('retryable_failure','failed','cancelled') AND last_failed_at IS NOT NULL AND (last_succeeded_at IS NULL OR last_failed_at >= last_succeeded_at) AND last_failure_category IS NOT NULL AND consecutive_failures > 0))
             """
           )
  end

  def down do
    drop_if_exists constraint(:acquisition_source_health, :source_health_state_invariant)

    create constraint(:acquisition_source_health, :source_health_state_invariant,
             check: """
               last_started_at IS NOT NULL AND ((last_status IS NULL AND last_succeeded_at IS NULL AND last_failed_at IS NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status = 'succeeded' AND last_succeeded_at IS NOT NULL AND last_failure_category IS NULL AND consecutive_failures = 0) OR (last_status IN ('retryable_failure','failed','cancelled') AND last_failed_at IS NOT NULL AND last_failure_category IS NOT NULL AND consecutive_failures > 0))
             """
           )

    drop_if_exists index(:acquisition_runs, [:started_at, :id])

    create index(:acquisition_runs, [:started_at, :id])
  end
end
