defmodule TcgCheap.Repo.Migrations.ExpandSinglesCatalogue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_printings) do
      add :details_synced_at, :utc_datetime_usec
      add :details_enrichment_failed_at, :utc_datetime_usec
      add :pricing_checked_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:card_printings) do
      remove :pricing_checked_at
      remove :details_enrichment_failed_at
      remove :details_synced_at
    end
  end
end
