defmodule TcgCheap.Repo.Migrations.CardPrintingMappingCorrectionHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_printings) do
      add :mapping_authority, :text, null: false, default: "provider"
    end

    create table(:card_printing_mapping_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event, :text, null: false
      add :from_status, :text
      add :to_status, :text, null: false
      add :from_cardmarket_product_id, :bigint
      add :cardmarket_product_id, :bigint
      add :mapping_authority, :text, null: false
      add :reason, :text
      add :source_mapping_evidence_at, :utc_datetime_usec
      add :printing_version_at, :utc_datetime_usec, null: false
      add :actor_type, :text, null: false
      add :actor_id, :uuid
      add :actor_email, :citext

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :card_printing_id,
          references(:card_printings,
            column: :id,
            name: "card_printing_mapping_decisions_card_printing_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:card_printing_mapping_decisions, [:card_printing_id, :inserted_at, :id])

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_transition_invariant,
             check: """
               (event = 'imported' AND from_status IS NULL) OR (event = 'baseline' AND from_status IS NULL) OR (event = 'provider_updated' AND from_status IS NOT NULL) OR (event = 'corrected' AND to_status = 'matched' AND from_status IS NOT NULL) OR (event = 'reopened' AND from_status IN ('matched', 'unmatched') AND to_status = 'review')
             """
           )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_state_invariant,
             check: """
               ((to_status = 'matched' AND cardmarket_product_id IS NOT NULL AND cardmarket_product_id > 0 AND reason IS NULL) OR (to_status IN ('pending', 'unmatched') AND cardmarket_product_id IS NULL AND reason IS NULL) OR (to_status = 'review' AND cardmarket_product_id IS NULL AND reason IS NOT NULL AND btrim(reason) <> ''))
             """
           )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_authority_invariant,
             check: """
               mapping_authority IN ('provider', 'administrator')
             """
           )

    create constraint(
             :card_printing_mapping_decisions,
             :card_printing_mapping_decisions_actor_invariant,
             check: """
               (actor_type = 'system' AND actor_id IS NULL AND actor_email IS NULL) OR (actor_type = 'administrator' AND actor_id IS NOT NULL AND actor_email IS NOT NULL AND btrim(actor_email) <> '')
             """
           )

    create constraint(:card_printings, :card_printings_mapping_authority_invariant,
             check: """
               mapping_authority IN ('provider', 'administrator')
             """
           )
  end

  def down do
    drop_if_exists constraint(:card_printings, :card_printings_mapping_authority_invariant)

    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_actor_invariant
                   )

    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_authority_invariant
                   )

    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_state_invariant
                   )

    drop_if_exists constraint(
                     :card_printing_mapping_decisions,
                     :card_printing_mapping_decisions_transition_invariant
                   )

    drop constraint(
           :card_printing_mapping_decisions,
           "card_printing_mapping_decisions_card_printing_id_fkey"
         )

    drop_if_exists index(:card_printing_mapping_decisions, [:card_printing_id, :inserted_at, :id])

    drop table(:card_printing_mapping_decisions)

    alter table(:card_printings) do
      remove :mapping_authority
    end
  end
end
