defmodule TcgCheap.Repo.Migrations.SealedListingObservations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sealed_listing_observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_title, :text, null: false
      add :normalized_title, :text, null: false
      add :direct_url, :text, null: false
      add :gtin, :text
      add :price_pln, :decimal
      add :currency, :text, null: false, default: "PLN"
      add :stock_status, :text, null: false, default: "unknown"
      add :observed_at, :utc_datetime_usec, null: false
      add :source_payload, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :retailer_listing_id,
          references(:retailer_listings,
            column: :id,
            name: "sealed_listing_observations_retailer_listing_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:sealed_listing_observations, [:retailer_listing_id, :observed_at, :id])

    create unique_index(:sealed_listing_observations, [:retailer_listing_id, :observed_at],
             name: "sealed_listing_observations_listing_observed_index"
           )

    create constraint(
             :sealed_listing_observations,
             :sealed_listing_observations_identity_invariant,
             check: """
               btrim(source_title) <> '' AND btrim(normalized_title) <> '' AND direct_url ~ '^https://[^/?#[:space:]]+(/|[/?#].*)?$'
             """
           )

    create constraint(:sealed_listing_observations, :sealed_listing_observations_gtin_invariant,
             check: """
               gtin IS NULL OR gtin ~ '^[0-9]+$' AND ((length(gtin) = 8 AND mod(10 - mod(3 * substring(gtin, 1, 1)::integer + 1 * substring(gtin, 2, 1)::integer + 3 * substring(gtin, 3, 1)::integer + 1 * substring(gtin, 4, 1)::integer + 3 * substring(gtin, 5, 1)::integer + 1 * substring(gtin, 6, 1)::integer + 3 * substring(gtin, 7, 1)::integer, 10), 10) = substring(gtin, 8, 1)::integer) OR (length(gtin) = 12 AND mod(10 - mod(3 * substring(gtin, 1, 1)::integer + 1 * substring(gtin, 2, 1)::integer + 3 * substring(gtin, 3, 1)::integer + 1 * substring(gtin, 4, 1)::integer + 3 * substring(gtin, 5, 1)::integer + 1 * substring(gtin, 6, 1)::integer + 3 * substring(gtin, 7, 1)::integer + 1 * substring(gtin, 8, 1)::integer + 3 * substring(gtin, 9, 1)::integer + 1 * substring(gtin, 10, 1)::integer + 3 * substring(gtin, 11, 1)::integer, 10), 10) = substring(gtin, 12, 1)::integer) OR (length(gtin) = 13 AND mod(10 - mod(1 * substring(gtin, 1, 1)::integer + 3 * substring(gtin, 2, 1)::integer + 1 * substring(gtin, 3, 1)::integer + 3 * substring(gtin, 4, 1)::integer + 1 * substring(gtin, 5, 1)::integer + 3 * substring(gtin, 6, 1)::integer + 1 * substring(gtin, 7, 1)::integer + 3 * substring(gtin, 8, 1)::integer + 1 * substring(gtin, 9, 1)::integer + 3 * substring(gtin, 10, 1)::integer + 1 * substring(gtin, 11, 1)::integer + 3 * substring(gtin, 12, 1)::integer, 10), 10) = substring(gtin, 13, 1)::integer) OR (length(gtin) = 14 AND mod(10 - mod(3 * substring(gtin, 1, 1)::integer + 1 * substring(gtin, 2, 1)::integer + 3 * substring(gtin, 3, 1)::integer + 1 * substring(gtin, 4, 1)::integer + 3 * substring(gtin, 5, 1)::integer + 1 * substring(gtin, 6, 1)::integer + 3 * substring(gtin, 7, 1)::integer + 1 * substring(gtin, 8, 1)::integer + 3 * substring(gtin, 9, 1)::integer + 1 * substring(gtin, 10, 1)::integer + 3 * substring(gtin, 11, 1)::integer + 1 * substring(gtin, 12, 1)::integer + 3 * substring(gtin, 13, 1)::integer, 10), 10) = substring(gtin, 14, 1)::integer))
             """
           )

    create constraint(
             :sealed_listing_observations,
             :sealed_listing_observations_currency_invariant,
             check: """
               currency = 'PLN'
             """
           )

    create constraint(
             :sealed_listing_observations,
             :sealed_listing_observations_stock_price_invariant,
             check: """
               stock_status IN ('in_stock', 'sold_out', 'unknown') AND (stock_status <> 'in_stock' OR (price_pln IS NOT NULL AND price_pln > 0))
             """
           )

    create constraint(
             :sealed_listing_observations,
             :sealed_listing_observations_price_finite_invariant,
             check: """
               price_pln IS NULL OR (price_pln > 0 AND price_pln <> 'NaN'::numeric AND price_pln <> 'Infinity'::numeric AND price_pln <> '-Infinity'::numeric)
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :sealed_listing_observations,
                     :sealed_listing_observations_price_finite_invariant
                   )

    drop_if_exists constraint(
                     :sealed_listing_observations,
                     :sealed_listing_observations_stock_price_invariant
                   )

    drop_if_exists constraint(
                     :sealed_listing_observations,
                     :sealed_listing_observations_currency_invariant
                   )

    drop_if_exists constraint(
                     :sealed_listing_observations,
                     :sealed_listing_observations_gtin_invariant
                   )

    drop_if_exists constraint(
                     :sealed_listing_observations,
                     :sealed_listing_observations_identity_invariant
                   )

    drop constraint(
           :sealed_listing_observations,
           "sealed_listing_observations_retailer_listing_id_fkey"
         )

    drop_if_exists unique_index(
                     :sealed_listing_observations,
                     [:retailer_listing_id, :observed_at],
                     name: "sealed_listing_observations_listing_observed_index"
                   )

    drop_if_exists index(:sealed_listing_observations, [:retailer_listing_id, :observed_at, :id])

    drop table(:sealed_listing_observations)
  end
end
