defmodule TcgCheap.Repo.Migrations.AddBoosterlandColligereSources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:retailer_listings, :retailer_listings_image_url_invariant)

    create constraint(:retailer_listings, :retailer_listings_image_url_invariant,
             check: """
                image_url IS NULL OR image_url ~* '^https://((assets\.tcgdex\.net|assets\.pokemon\.com|www\.pokemon\.com|mcdn\.pokemon\.com)|([a-z0-9-]+\.)*(lootquest\.pl|cardzhouse\.pl|boosterpoint\.pl|pokebooster\.pl|boosterland\.pl|colligere\.pl))(:443)?(/|[/?#][^[:space:][:cntrl:]]*)?$'
             """
           )

    drop_if_exists constraint(:sealed_products, :sealed_products_image_provenance_invariant)

    create constraint(:sealed_products, :sealed_products_image_provenance_invariant,
             check: """
                ((image_url IS NULL AND image_source IS NULL AND image_source_url IS NULL) OR (image_url IS NOT NULL AND image_source IS NOT NULL AND image_source_url IS NOT NULL AND image_url ~* '^https://((assets\.tcgdex\.net|assets\.pokemon\.com|www\.pokemon\.com|mcdn\.pokemon\.com)|([a-z0-9-]+\.)*(lootquest\.pl|cardzhouse\.pl|boosterpoint\.pl|pokebooster\.pl|boosterland\.pl|colligere\.pl))(:443)?(/|[/?#][^[:space:][:cntrl:]]*)?$' AND btrim(image_source) <> '' AND image_source_url ~ '^https://[^/@/?#[:space:]]+(/|[/?#].*)?$'))
             """
           )
  end

  def down, do: raise("forward-only migration")
end
