defmodule TcgCheap.Repo.Migrations.HardenProviderCircuitEvidence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:acquisition_source_health, :source_health_circuit_open_invariant)

    create constraint(:acquisition_source_health, :source_health_circuit_open_invariant,
             check: """
               (circuit_opened_at IS NULL AND ((last_status IS NULL AND circuit_failure_streak = 0) OR (last_status = 'succeeded' AND circuit_failure_streak = 0) OR (last_status IS NOT NULL AND last_status IN ('retryable_failure','failed','cancelled')))) OR (circuit_opened_at IS NOT NULL AND circuit_failure_streak > 0 AND last_failed_at IS NOT NULL AND circuit_opened_at <= last_failed_at)
             """
           )
  end

  def down do
    drop_if_exists constraint(:acquisition_source_health, :source_health_circuit_open_invariant)

    create constraint(:acquisition_source_health, :source_health_circuit_open_invariant,
             check: """
               circuit_opened_at IS NULL OR circuit_failure_streak > 0
             """
           )
  end
end
