defmodule TcgCheap.Repo.Migrations.HomepageDiscoveryIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:single_valuation_snapshots, [:policy_version, :fetched_at, :card_printing_id],
             name: "single_valuation_snapshots_homepage_window_index"
           )
  end

  def down do
    drop_if_exists index(
                     :single_valuation_snapshots,
                     [:policy_version, :fetched_at, :card_printing_id],
                     name: "single_valuation_snapshots_homepage_window_index"
                   )
  end
end
