defmodule TcgCheap.Repo.Migrations.CardmarketBulkV1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_operation_invariant)

    create constraint(:acquisition_runs, :acquisition_runs_operation_invariant,
             check: """
               operation IN ('single_valuation','exchange_rate','sealed_retailer_refresh','card_catalogue_sync','card_catalogue_enrichment','cardmarket_bulk_sync')
             """
           )

    create table(:cardmarket_bulk_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :policy_version, :text, null: false
      add :parser_version, :text, null: false
      add :product_created_at, :utc_datetime_usec, null: false
      add :price_created_at, :utc_datetime_usec, null: false
      add :fetched_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec, null: false
      add :product_sha256, :text, null: false
      add :price_sha256, :text, null: false
      add :product_byte_size, :bigint, null: false
      add :price_byte_size, :bigint, null: false
      add :product_row_count, :bigint, null: false
      add :price_row_count, :bigint, null: false
      add :singles_price_row_count, :bigint, null: false
      add :priceable_singles_count, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :cardmarket_bulk_batches,
             [
               :policy_version,
               :product_created_at,
               :price_created_at,
               :product_sha256,
               :price_sha256
             ],
             name: "cardmarket_bulk_batches_unique_import_index"
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_versions_present,
             check: """
               btrim(policy_version) <> '' AND btrim(parser_version) <> ''
             """
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_hashes_hex,
             check: """
               product_sha256 ~ '^[0-9a-fA-F]{64}$' AND price_sha256 ~ '^[0-9a-fA-F]{64}$'
             """
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_counts_coherent,
             check: """
               product_row_count > 0 AND price_row_count > 0 AND singles_price_row_count > 0 AND priceable_singles_count > 0 AND price_row_count >= singles_price_row_count AND product_row_count = singles_price_row_count AND priceable_singles_count <= singles_price_row_count
             """
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_sizes_positive,
             check: """
               product_byte_size > 0 AND price_byte_size > 0
             """
           )

    create constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_timestamps_coherent,
             check: """
               fetched_at >= product_created_at AND fetched_at >= price_created_at AND completed_at >= fetched_at
             """
           )

    create table(:cardmarket_bulk_prices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :cardmarket_product_id, :bigint, null: false
      add :category_id, :bigint, null: false, default: 51
      add :avg, :decimal
      add :low, :decimal
      add :trend, :decimal
      add :avg1, :decimal
      add :avg7, :decimal
      add :avg30, :decimal
      add :avg_holo, :decimal
      add :low_holo, :decimal
      add :trend_holo, :decimal
      add :avg1_holo, :decimal
      add :avg7_holo, :decimal
      add :avg30_holo, :decimal
      add :selected_metric, :text
      add :selected_value_eur, :decimal
      add :source_updated_at, :utc_datetime_usec, null: false

      add :last_batch_id,
          references(:cardmarket_bulk_batches,
            column: :id,
            name: "cardmarket_bulk_prices_last_batch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:cardmarket_bulk_prices, [:cardmarket_product_id],
             name: "cardmarket_bulk_prices_unique_cardmarket_product_id_index"
           )

    create constraint(:cardmarket_bulk_prices, :cardmarket_bulk_prices_pokemon_category,
             check: """
               cardmarket_product_id > 0 AND category_id = 51
             """
           )

    create constraint(:cardmarket_bulk_prices, :cardmarket_bulk_prices_selected_metric_coherence,
             check: """
               ((selected_metric IS NULL AND selected_value_eur IS NULL) OR (selected_metric IS NOT NULL AND selected_value_eur IS NOT NULL)) AND (selected_metric IS NULL OR selected_metric IN ('avg7', 'avg30', 'trend', 'avg', 'low'))
             """
           )

    create constraint(:cardmarket_bulk_prices, :cardmarket_bulk_prices_values_positive_finite,
             check: """
               (avg IS NULL OR (avg > 0 AND avg <> 'NaN' AND avg <> 'Infinity' AND avg <> '-Infinity')) AND (low IS NULL OR (low > 0 AND low <> 'NaN' AND low <> 'Infinity' AND low <> '-Infinity')) AND (trend IS NULL OR (trend > 0 AND trend <> 'NaN' AND trend <> 'Infinity' AND trend <> '-Infinity')) AND (avg1 IS NULL OR (avg1 > 0 AND avg1 <> 'NaN' AND avg1 <> 'Infinity' AND avg1 <> '-Infinity')) AND (avg7 IS NULL OR (avg7 > 0 AND avg7 <> 'NaN' AND avg7 <> 'Infinity' AND avg7 <> '-Infinity')) AND (avg30 IS NULL OR (avg30 > 0 AND avg30 <> 'NaN' AND avg30 <> 'Infinity' AND avg30 <> '-Infinity')) AND (avg_holo IS NULL OR (avg_holo > 0 AND avg_holo <> 'NaN' AND avg_holo <> 'Infinity' AND avg_holo <> '-Infinity')) AND (low_holo IS NULL OR (low_holo > 0 AND low_holo <> 'NaN' AND low_holo <> 'Infinity' AND low_holo <> '-Infinity')) AND (trend_holo IS NULL OR (trend_holo > 0 AND trend_holo <> 'NaN' AND trend_holo <> 'Infinity' AND trend_holo <> '-Infinity')) AND (avg1_holo IS NULL OR (avg1_holo > 0 AND avg1_holo <> 'NaN' AND avg1_holo <> 'Infinity' AND avg1_holo <> '-Infinity')) AND (avg7_holo IS NULL OR (avg7_holo > 0 AND avg7_holo <> 'NaN' AND avg7_holo <> 'Infinity' AND avg7_holo <> '-Infinity')) AND (avg30_holo IS NULL OR (avg30_holo > 0 AND avg30_holo <> 'NaN' AND avg30_holo <> 'Infinity' AND avg30_holo <> '-Infinity')) AND (selected_value_eur IS NULL OR (selected_value_eur > 0 AND selected_value_eur <> 'NaN' AND selected_value_eur <> 'Infinity' AND selected_value_eur <> '-Infinity'))
             """
           )

    create index(:cardmarket_bulk_prices, [:last_batch_id])

    create table(:cardmarket_bulk_products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :cardmarket_product_id, :bigint, null: false
      add :name, :text, null: false
      add :category_id, :bigint, null: false, default: 51
      add :category_name, :text, null: false, default: "Pokémon Single"
      add :expansion_id, :bigint, null: false
      add :metacard_id, :bigint, null: false
      add :source_date_added, :text, null: false
      add :source_updated_at, :utc_datetime_usec, null: false

      add :last_batch_id,
          references(:cardmarket_bulk_batches,
            column: :id,
            name: "cardmarket_bulk_products_last_batch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:cardmarket_bulk_products, [:cardmarket_product_id],
             name: "cardmarket_bulk_products_unique_cardmarket_product_id_index"
           )

    create constraint(:cardmarket_bulk_products, :cardmarket_bulk_products_identity_invariant,
             check: """
               cardmarket_product_id > 0 AND category_id = 51 AND category_name = 'Pokémon Single' AND expansion_id > 0 AND metacard_id >= 0
             """
           )

    create constraint(:cardmarket_bulk_products, :cardmarket_bulk_products_text_present,
             check: """
               btrim(name) <> '' AND btrim(source_date_added) <> ''
             """
           )

    create index(:cardmarket_bulk_products, [:last_batch_id])

    create table(:cardmarket_bulk_raw_responses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :endpoint_kind, :text, null: false
      add :source_url, :text, null: false
      add :content_type, :text, null: false, default: "application/json"
      add :content_encoding, :text, null: false, default: "gzip"
      add :source_byte_size, :bigint, null: false
      add :compressed_byte_size, :bigint, null: false
      add :sha256, :text, null: false
      add :body, :binary, null: false
      add :fetched_at, :utc_datetime_usec, null: false
      add :upstream_created_at, :utc_datetime_usec, null: false

      add :batch_id,
          references(:cardmarket_bulk_batches,
            column: :id,
            name: "cardmarket_bulk_raw_responses_batch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:cardmarket_bulk_raw_responses, [:batch_id, :endpoint_kind],
             name: "cardmarket_bulk_raw_responses_unique_batch_endpoint_index"
           )

    create constraint(
             :cardmarket_bulk_raw_responses,
             :cardmarket_bulk_raw_responses_kind_invariant,
             check: """
               endpoint_kind IN ('products', 'prices') AND content_type = 'application/json' AND content_encoding = 'gzip'
             """
           )

    create constraint(
             :cardmarket_bulk_raw_responses,
             :cardmarket_bulk_raw_responses_url_invariant,
             check: """
               (endpoint_kind = 'products' AND source_url = 'https://downloads.s3.cardmarket.com/productCatalog/productList/products_singles_6.json') OR (endpoint_kind = 'prices' AND source_url = 'https://downloads.s3.cardmarket.com/productCatalog/priceGuide/price_guide_6.json')
             """
           )

    create constraint(
             :cardmarket_bulk_raw_responses,
             :cardmarket_bulk_raw_responses_body_invariant,
             check: """
               source_byte_size > 0 AND compressed_byte_size > 0 AND octet_length(body) = compressed_byte_size
             """
           )

    create constraint(:cardmarket_bulk_raw_responses, :cardmarket_bulk_raw_responses_hash_hex,
             check: """
               sha256 ~ '^[0-9a-fA-F]{64}$'
             """
           )

    create constraint(
             :cardmarket_bulk_raw_responses,
             :cardmarket_bulk_raw_responses_timestamps_coherent,
             check: """
               fetched_at >= upstream_created_at
             """
           )

    create index(:cardmarket_bulk_raw_responses, [:batch_id])
  end

  def down do
    drop_if_exists index(:cardmarket_bulk_raw_responses, [:batch_id])

    drop_if_exists constraint(
                     :cardmarket_bulk_raw_responses,
                     :cardmarket_bulk_raw_responses_timestamps_coherent
                   )

    drop_if_exists constraint(
                     :cardmarket_bulk_raw_responses,
                     :cardmarket_bulk_raw_responses_hash_hex
                   )

    drop_if_exists constraint(
                     :cardmarket_bulk_raw_responses,
                     :cardmarket_bulk_raw_responses_body_invariant
                   )

    drop_if_exists constraint(
                     :cardmarket_bulk_raw_responses,
                     :cardmarket_bulk_raw_responses_url_invariant
                   )

    drop_if_exists constraint(
                     :cardmarket_bulk_raw_responses,
                     :cardmarket_bulk_raw_responses_kind_invariant
                   )

    drop constraint(:cardmarket_bulk_raw_responses, "cardmarket_bulk_raw_responses_batch_id_fkey")

    drop_if_exists unique_index(:cardmarket_bulk_raw_responses, [:batch_id, :endpoint_kind],
                     name: "cardmarket_bulk_raw_responses_unique_batch_endpoint_index"
                   )

    drop table(:cardmarket_bulk_raw_responses)

    drop_if_exists index(:cardmarket_bulk_products, [:last_batch_id])

    drop_if_exists constraint(:cardmarket_bulk_products, :cardmarket_bulk_products_text_present)

    drop_if_exists constraint(
                     :cardmarket_bulk_products,
                     :cardmarket_bulk_products_identity_invariant
                   )

    drop constraint(:cardmarket_bulk_products, "cardmarket_bulk_products_last_batch_id_fkey")

    drop_if_exists unique_index(:cardmarket_bulk_products, [:cardmarket_product_id],
                     name: "cardmarket_bulk_products_unique_cardmarket_product_id_index"
                   )

    drop table(:cardmarket_bulk_products)

    drop_if_exists index(:cardmarket_bulk_prices, [:last_batch_id])

    drop_if_exists constraint(
                     :cardmarket_bulk_prices,
                     :cardmarket_bulk_prices_values_positive_finite
                   )

    drop_if_exists constraint(
                     :cardmarket_bulk_prices,
                     :cardmarket_bulk_prices_selected_metric_coherence
                   )

    drop_if_exists constraint(:cardmarket_bulk_prices, :cardmarket_bulk_prices_pokemon_category)

    drop constraint(:cardmarket_bulk_prices, "cardmarket_bulk_prices_last_batch_id_fkey")

    drop_if_exists unique_index(:cardmarket_bulk_prices, [:cardmarket_product_id],
                     name: "cardmarket_bulk_prices_unique_cardmarket_product_id_index"
                   )

    drop table(:cardmarket_bulk_prices)

    drop_if_exists constraint(
                     :cardmarket_bulk_batches,
                     :cardmarket_bulk_batches_timestamps_coherent
                   )

    drop_if_exists constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_sizes_positive)

    drop_if_exists constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_counts_coherent)

    drop_if_exists constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_hashes_hex)

    drop_if_exists constraint(:cardmarket_bulk_batches, :cardmarket_bulk_batches_versions_present)

    drop_if_exists unique_index(
                     :cardmarket_bulk_batches,
                     [
                       :policy_version,
                       :product_created_at,
                       :price_created_at,
                       :product_sha256,
                       :price_sha256
                     ],
                     name: "cardmarket_bulk_batches_unique_import_index"
                   )

    drop table(:cardmarket_bulk_batches)

    drop_if_exists constraint(:acquisition_runs, :acquisition_runs_operation_invariant)

    create constraint(:acquisition_runs, :acquisition_runs_operation_invariant,
             check: """
               operation IN ('single_valuation','exchange_rate','sealed_retailer_refresh','card_catalogue_sync','card_catalogue_enrichment')
             """
           )
  end
end
