defmodule TcgCheap.Repo.Migrations.PublicSealedLookup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:sealed_products, ["search_name gin_trgm_ops"],
             name: "sealed_products_search_name_trgm_index",
             concurrently: true,
             using: "gin"
           )

    create index(:sealed_product_aliases, ["normalized_value gin_trgm_ops"],
             name: "sealed_product_aliases_normalized_value_trgm_index",
             concurrently: true,
             using: "gin"
           )
  end

  def down do
    drop_if_exists index(:sealed_product_aliases, ["normalized_value gin_trgm_ops"],
                     name: "sealed_product_aliases_normalized_value_trgm_index"
                   )

    drop_if_exists index(:sealed_products, ["search_name gin_trgm_ops"],
                     name: "sealed_products_search_name_trgm_index"
                   )
  end
end
