defmodule TcgCheap.Repo.Migrations.AddExchangeRates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:exchange_rates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false, default: "nbp"
      add :table, :text, null: false, default: "A"
      add :base_currency, :text, null: false, default: "EUR"
      add :quote_currency, :text, null: false, default: "PLN"
      add :rate, :decimal, null: false
      add :effective_date, :date, null: false
      add :publication_number, :text, null: false
      add :fetched_at, :utc_datetime_usec, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:exchange_rates, [
             :source,
             :table,
             :base_currency,
             :quote_currency,
             :effective_date,
             :fetched_at
           ])

    create unique_index(
             :exchange_rates,
             [:source, :table, :base_currency, :quote_currency, :effective_date],
             name: "exchange_rates_canonical_observation_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :exchange_rates,
                     [:source, :table, :base_currency, :quote_currency, :effective_date],
                     name: "exchange_rates_canonical_observation_index"
                   )

    drop_if_exists index(:exchange_rates, [
                     :source,
                     :table,
                     :base_currency,
                     :quote_currency,
                     :effective_date,
                     :fetched_at
                   ])

    drop table(:exchange_rates)
  end
end
