defmodule TcgCheap.Repo.Migrations.SealedBuyingGuideSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sealed_buying_guide_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :guide_date, :date, null: false
      add :model_version, :text, null: false
      add :currency, :text, null: false, default: "PLN"
      add :status, :text, null: false
      add :limited_reason, :text
      add :reference_price_pln, :decimal
      add :great_price_max_pln, :decimal
      add :fair_price_max_pln, :decimal
      add :expensive_price_max_pln, :decimal
      add :confidence, :decimal, null: false
      add :trend, :text, null: false
      add :trend_change, :decimal
      add :availability, :text, null: false
      add :availability_trend, :text, null: false
      add :regular_benchmark_pln, :decimal
      add :msrp_pln, :decimal
      add :lgs_median_pln, :decimal
      add :sold_out_center_pln, :decimal
      add :explanation_factors, {:array, :text}, null: false
      add :source_aggregate_calculated_at, :utc_datetime_usec, null: false
      add :calculated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sealed_product_id,
          references(:sealed_products,
            column: :id,
            name: "sealed_buying_guide_snapshots_sealed_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :source_aggregate_id,
          references(:sealed_daily_aggregates,
            column: :id,
            name: "sealed_buying_guide_snapshots_source_aggregate_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(
             :sealed_buying_guide_snapshots,
             [:sealed_product_id, :guide_date, :model_version],
             name: "sealed_buying_guide_snapshots_unique_product_date_version_index"
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_version_invariant,
             check: """
               model_version ~ '^sealed_buying_model_v[0-9]+$'
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_currency_invariant,
             check: """
               currency = 'PLN'
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_state_invariant,
             check: """
               (status = 'ready' AND limited_reason IS NULL AND reference_price_pln > 0 AND great_price_max_pln > 0 AND fair_price_max_pln > great_price_max_pln AND expensive_price_max_pln > fair_price_max_pln) OR (status = 'limited' AND limited_reason IN ('uncertain_mapping','limited_market_aggregate','stale_market_evidence','insufficient_history','low_confidence','invalid_band_boundaries') AND great_price_max_pln IS NULL AND fair_price_max_pln IS NULL AND expensive_price_max_pln IS NULL)
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_money_invariant,
             check: """
               (reference_price_pln IS NULL OR (reference_price_pln > 0 AND reference_price_pln <> 'NaN'::numeric AND reference_price_pln <> 'Infinity'::numeric AND reference_price_pln <> '-Infinity'::numeric)) AND (regular_benchmark_pln IS NULL OR (regular_benchmark_pln > 0 AND regular_benchmark_pln <> 'NaN'::numeric AND regular_benchmark_pln <> 'Infinity'::numeric AND regular_benchmark_pln <> '-Infinity'::numeric)) AND (msrp_pln IS NULL OR (msrp_pln > 0 AND msrp_pln <> 'NaN'::numeric AND msrp_pln <> 'Infinity'::numeric AND msrp_pln <> '-Infinity'::numeric)) AND (lgs_median_pln IS NULL OR (lgs_median_pln > 0 AND lgs_median_pln <> 'NaN'::numeric AND lgs_median_pln <> 'Infinity'::numeric AND lgs_median_pln <> '-Infinity'::numeric)) AND (sold_out_center_pln IS NULL OR (sold_out_center_pln > 0 AND sold_out_center_pln <> 'NaN'::numeric AND sold_out_center_pln <> 'Infinity'::numeric AND sold_out_center_pln <> '-Infinity'::numeric)) AND (great_price_max_pln IS NULL OR (great_price_max_pln > 0 AND great_price_max_pln <> 'NaN'::numeric AND great_price_max_pln <> 'Infinity'::numeric AND great_price_max_pln <> '-Infinity'::numeric)) AND (fair_price_max_pln IS NULL OR (fair_price_max_pln > 0 AND fair_price_max_pln <> 'NaN'::numeric AND fair_price_max_pln <> 'Infinity'::numeric AND fair_price_max_pln <> '-Infinity'::numeric)) AND (expensive_price_max_pln IS NULL OR (expensive_price_max_pln > 0 AND expensive_price_max_pln <> 'NaN'::numeric AND expensive_price_max_pln <> 'Infinity'::numeric AND expensive_price_max_pln <> '-Infinity'::numeric))
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_confidence_invariant,
             check: """
               confidence >= 0 AND confidence <= 1 AND confidence <> 'NaN'::numeric AND confidence <> 'Infinity'::numeric AND confidence <> '-Infinity'::numeric
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_trend_invariant,
             check: """
               (trend = 'insufficient_history' AND trend_change IS NULL) OR (trend IN ('rising','stable','falling') AND trend_change > -1 AND trend_change <> 'NaN'::numeric AND trend_change <> 'Infinity'::numeric AND trend_change <> '-Infinity'::numeric)
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_availability_invariant,
             check: """
               availability IN ('abundant','balanced','scarce') AND availability_trend IN ('improving','stable','tightening','insufficient_history')
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_factors_invariant,
             check: """
               cardinality(explanation_factors) BETWEEN 1 AND 8 AND explanation_factors <@ ARRAY['market_benchmark','market_data_limited','msrp','lgs','sold_out','trend_rising','trend_stable','trend_falling','trend_insufficient_history','availability_abundant','availability_balanced','availability_scarce','availability_trend_improving','availability_trend_stable','availability_trend_tightening','availability_trend_insufficient_history']::text[]
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_time_invariant,
             check: """
               guide_date <= calculated_at::date AND source_aggregate_calculated_at <= calculated_at
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_time_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_factors_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_availability_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_trend_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_confidence_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_money_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_state_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_currency_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_version_invariant
                   )

    drop constraint(
           :sealed_buying_guide_snapshots,
           "sealed_buying_guide_snapshots_sealed_product_id_fkey"
         )

    drop constraint(
           :sealed_buying_guide_snapshots,
           "sealed_buying_guide_snapshots_source_aggregate_id_fkey"
         )

    drop_if_exists unique_index(
                     :sealed_buying_guide_snapshots,
                     [:sealed_product_id, :guide_date, :model_version],
                     name: "sealed_buying_guide_snapshots_unique_product_date_version_index"
                   )

    drop table(:sealed_buying_guide_snapshots)
  end
end
