defmodule TcgCheap.Repo.Migrations.PersistedSealedBuyingGuides do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sealed_daily_aggregates) do
      add :source_evidence, {:array, :map}, null: false, default: []
    end

    alter table(:sealed_buying_guide_snapshots) do
      add :source_aggregate_fingerprint, :text, null: false
    end

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_trend_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_time_invariant
                   )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_trend_invariant,
             check: """
               (trend = 'insufficient_history' AND trend_change IS NULL) OR (trend IN ('rising','stable','falling') AND trend_change IS NOT NULL AND trend_change > -1 AND trend_change <> 'NaN'::numeric AND trend_change <> 'Infinity'::numeric AND trend_change <> '-Infinity'::numeric)
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_time_invariant,
             check: """
               guide_date = source_aggregate_calculated_at::date AND source_aggregate_calculated_at <= calculated_at
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_fingerprint_invariant,
             check: """
               source_aggregate_fingerprint ~ '^[0-9a-f]{64}$'
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_fingerprint_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_time_invariant
                   )

    drop_if_exists constraint(
                     :sealed_buying_guide_snapshots,
                     :sealed_buying_guide_snapshots_trend_invariant
                   )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_time_invariant,
             check: """
               guide_date <= calculated_at::date AND source_aggregate_calculated_at <= calculated_at
             """
           )

    create constraint(
             :sealed_buying_guide_snapshots,
             :sealed_buying_guide_snapshots_trend_invariant,
             check: """
               (trend = 'insufficient_history' AND trend_change IS NULL) OR (trend IN ('rising','stable','falling') AND trend_change > -1 AND trend_change <> 'NaN'::numeric AND trend_change <> 'Infinity'::numeric AND trend_change <> '-Infinity'::numeric)
             """
           )

    alter table(:sealed_buying_guide_snapshots) do
      remove :source_aggregate_fingerprint
    end

    alter table(:sealed_daily_aggregates) do
      remove :source_evidence
    end
  end
end
