defmodule TcgCheap.Repo.Migrations.AppendCardmarketMappingEvidenceDecisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(
                     :cardmarket_card_mapping_evidence,
                     [:source_batch_id, :expansion_mapping_id, :card_printing_id],
                     name: "cm_card_evidence_batch_mapping_printing_idx"
                   )

    create unique_index(
             :cardmarket_card_mapping_evidence,
             [
               :source_batch_id,
               :expansion_mapping_id,
               :card_printing_id,
               :decision,
               :cardmarket_product_id
             ],
             name: "cm_card_evidence_batch_mapping_decision_product_idx",
             nulls_distinct: false
           )
  end

  def down do
    raise "This migration is forward-only: appended review and anchor evidence cannot satisfy the old unique index"
  end
end
