defmodule TcgCheap.Repo.Migrations.SealedRetailerImportDiagnostics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:import_issues, :import_issues_provider_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_operation_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_stage_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_target_type_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_operation_stage_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_stage_target_invariant)

    create constraint(:import_issues, :import_issues_provider_invariant,
             check: """
               provider_key = 'tcgdex_catalogue' OR provider_key ~ '^sealed_retailer:[A-Za-z0-9][A-Za-z0-9._-]{0,143}$'
             """
           )

    create constraint(:import_issues, :import_issues_provider_operation_invariant,
             check: """
               (provider_key = 'tcgdex_catalogue' AND operation IN ('card_catalogue_sync','card_catalogue_enrichment')) OR (provider_key ~ '^sealed_retailer:[A-Za-z0-9][A-Za-z0-9._-]{0,143}$' AND operation = 'sealed_retailer_refresh')
             """
           )

    create constraint(:import_issues, :import_issues_operation_invariant,
             check: """
               operation IN ('card_catalogue_sync','card_catalogue_enrichment','sealed_retailer_refresh')
             """
           )

    create constraint(:import_issues, :import_issues_stage_invariant,
             check: """
               stage IN ('catalogue_fetch','catalogue_validation','set_fetch','set_validation','set_import','card_fetch','card_import','retailer_fetch','listing_validation','listing_import')
             """
           )

    create constraint(:import_issues, :import_issues_target_type_invariant,
             check: """
               target_type IN ('catalogue','set','card','retailer')
             """
           )

    create constraint(:import_issues, :import_issues_operation_stage_invariant,
             check: """
               (operation = 'card_catalogue_sync' AND stage IN ('catalogue_fetch','catalogue_validation','set_fetch','set_validation','set_import')) OR (operation = 'card_catalogue_enrichment' AND stage IN ('set_fetch','set_validation','set_import','card_fetch','card_import')) OR (operation = 'sealed_retailer_refresh' AND stage IN ('retailer_fetch','listing_validation','listing_import'))
             """
           )

    create constraint(:import_issues, :import_issues_stage_target_invariant,
             check: """
               (stage IN ('catalogue_fetch','catalogue_validation') AND target_type = 'catalogue' AND target_key = 'tcgdex') OR (stage IN ('set_fetch','set_validation','set_import') AND target_type = 'set') OR (stage IN ('card_fetch','card_import') AND target_type = 'card') OR (stage IN ('retailer_fetch','listing_validation','listing_import') AND target_type = 'retailer' AND target_key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND target_key = lower(target_key))
             """
           )
  end

  def down do
    drop_if_exists constraint(:import_issues, :import_issues_stage_target_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_operation_stage_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_target_type_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_stage_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_operation_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_provider_operation_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_provider_invariant)

    execute("""
    DELETE FROM import_issues
    WHERE provider_key LIKE 'sealed_retailer:%'
       OR operation = 'sealed_retailer_refresh'
       OR stage IN ('retailer_fetch', 'listing_validation', 'listing_import')
       OR target_type = 'retailer'
    """)

    create constraint(:import_issues, :import_issues_stage_target_invariant,
             check: """
               (stage IN ('catalogue_fetch','catalogue_validation') AND target_type = 'catalogue' AND target_key = 'tcgdex') OR (stage IN ('set_fetch','set_validation','set_import') AND target_type = 'set') OR (stage IN ('card_fetch','card_import') AND target_type = 'card')
             """
           )

    create constraint(:import_issues, :import_issues_operation_stage_invariant,
             check: """
               (operation = 'card_catalogue_sync' AND stage IN ('catalogue_fetch','catalogue_validation','set_fetch','set_validation','set_import')) OR (operation = 'card_catalogue_enrichment' AND stage IN ('set_fetch','set_validation','set_import','card_fetch','card_import'))
             """
           )

    create constraint(:import_issues, :import_issues_target_type_invariant,
             check: """
               target_type IN ('catalogue','set','card')
             """
           )

    create constraint(:import_issues, :import_issues_stage_invariant,
             check: """
               stage IN ('catalogue_fetch','catalogue_validation','set_fetch','set_validation','set_import','card_fetch','card_import')
             """
           )

    create constraint(:import_issues, :import_issues_operation_invariant,
             check: """
               operation IN ('card_catalogue_sync','card_catalogue_enrichment')
             """
           )

    create constraint(:import_issues, :import_issues_provider_invariant,
             check: """
               provider_key = 'tcgdex_catalogue'
             """
           )
  end
end
