defmodule TcgCheap.Repo.Migrations.AddNormalizedCardPrintingSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_printings) do
      add :search_name, :text, null: false, default: ""
      add :search_set_name, :text, null: false, default: ""
      add :search_collector_number, :text, null: false, default: ""
      add :search_tcgdex_id, :text, null: false, default: ""
    end

    execute("""
    UPDATE card_printings SET search_name = btrim(lower(regexp_replace(normalize(name, NFKC) COLLATE "pg_unicode_fast", '[[:space:]]+', ' ', 'g'))), search_set_name = btrim(lower(regexp_replace(normalize(set_name, NFKC) COLLATE "pg_unicode_fast", '[[:space:]]+', ' ', 'g'))), search_collector_number = btrim(lower(regexp_replace(normalize(collector_number, NFKC) COLLATE "pg_unicode_fast", '[[:space:]]+', ' ', 'g'))), search_tcgdex_id = btrim(lower(regexp_replace(normalize(tcgdex_id, NFKC) COLLATE "pg_unicode_fast", '[[:space:]]+', ' ', 'g')));
    """)
  end

  def down do
    execute("""
    UPDATE card_printings SET search_name = '', search_set_name = '', search_collector_number = '', search_tcgdex_id = '';
    """)

    alter table(:card_printings) do
      remove :search_tcgdex_id
      remove :search_collector_number
      remove :search_set_name
      remove :search_name
    end
  end
end
