defmodule TcgCheap.Repo.Migrations.ImportIssueDiagnostics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:import_issues, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_key, :text, null: false
      add :operation, :text, null: false
      add :stage, :text, null: false
      add :target_type, :text, null: false
      add :target_key, :text, null: false
      add :issue_kind, :text, null: false
      add :issue_code, :text, null: false
      add :first_seen_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:import_issues, [:last_seen_at, :id])

    create unique_index(
             :import_issues,
             [
               :provider_key,
               :operation,
               :stage,
               :target_type,
               :target_key,
               :issue_kind,
               :issue_code
             ],
             name: "import_issues_unique_import_issue_index"
           )

    create constraint(:import_issues, :import_issues_text_invariant,
             check: """
               btrim(provider_key) <> '' AND btrim(target_key) <> ''
             """
           )

    create constraint(:import_issues, :import_issues_provider_invariant,
             check: """
               provider_key = 'tcgdex_catalogue'
             """
           )

    create constraint(:import_issues, :import_issues_operation_invariant,
             check: """
               operation IN ('card_catalogue_sync','card_catalogue_enrichment')
             """
           )

    create constraint(:import_issues, :import_issues_stage_invariant,
             check: """
               stage IN ('catalogue_fetch','catalogue_validation','set_fetch','set_validation','set_import','card_fetch','card_import')
             """
           )

    create constraint(:import_issues, :import_issues_target_type_invariant,
             check: """
               target_type IN ('catalogue','set','card')
             """
           )

    create constraint(:import_issues, :import_issues_kind_invariant,
             check: """
               issue_kind IN ('unmatched','ambiguous','malformed','failed')
             """
           )

    create constraint(:import_issues, :import_issues_code_invariant,
             check: """
               issue_code IN ('malformed_response','budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown')
             """
           )

    create constraint(:import_issues, :import_issues_operation_stage_invariant,
             check: """
               (operation = 'card_catalogue_sync' AND stage IN ('catalogue_fetch','catalogue_validation','set_fetch','set_validation','set_import')) OR (operation = 'card_catalogue_enrichment' AND stage IN ('set_fetch','set_validation','set_import','card_fetch','card_import'))
             """
           )

    create constraint(:import_issues, :import_issues_stage_target_invariant,
             check: """
               (stage IN ('catalogue_fetch','catalogue_validation') AND target_type = 'catalogue' AND target_key = 'tcgdex') OR (stage IN ('set_fetch','set_validation','set_import') AND target_type = 'set') OR (stage IN ('card_fetch','card_import') AND target_type = 'card')
             """
           )

    create constraint(:import_issues, :import_issues_kind_code_invariant,
             check: """
               (issue_kind IN ('unmatched','ambiguous') AND issue_code = 'provider_response') OR (issue_kind = 'malformed' AND issue_code = 'malformed_response') OR (issue_kind = 'failed' AND issue_code IN ('budget','rate_limit','timeout','transport','provider_response','persistence','configuration','local_input','unknown'))
             """
           )

    create constraint(:import_issues, :import_issues_timestamp_invariant,
             check: """
               last_seen_at >= first_seen_at
             """
           )
  end

  def down do
    drop_if_exists constraint(:import_issues, :import_issues_timestamp_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_kind_code_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_stage_target_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_operation_stage_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_code_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_kind_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_target_type_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_stage_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_operation_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_provider_invariant)

    drop_if_exists constraint(:import_issues, :import_issues_text_invariant)

    drop_if_exists unique_index(
                     :import_issues,
                     [
                       :provider_key,
                       :operation,
                       :stage,
                       :target_type,
                       :target_key,
                       :issue_kind,
                       :issue_code
                     ],
                     name: "import_issues_unique_import_issue_index"
                   )

    drop_if_exists index(:import_issues, [:last_seen_at, :id])

    drop table(:import_issues)
  end
end
