defmodule TcgCheap.Repo.Migrations.AcquisitionBudgetLimitOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_request_limits_invariant
                   )

    create constraint(
             :acquisition_data_providers,
             :acquisition_data_providers_request_limits_invariant,
             check: """
               hourly_request_limit > 0 AND daily_request_limit > 0 AND monthly_request_limit > 0
             """
           )

    create constraint(
             :acquisition_data_providers,
             :acquisition_data_providers_request_limit_order_invariant,
             check: """
               hourly_request_limit <= daily_request_limit AND daily_request_limit <= monthly_request_limit
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_request_limit_order_invariant
                   )

    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_request_limits_invariant
                   )

    create constraint(
             :acquisition_data_providers,
             :acquisition_data_providers_request_limits_invariant,
             check: """
               hourly_request_limit > 0 AND daily_request_limit > 0 AND monthly_request_limit > 0 AND hourly_request_limit <= daily_request_limit AND daily_request_limit <= monthly_request_limit
             """
           )
  end
end
