defmodule TcgCheap.Repo.Migrations.AcquisitionBudgetControl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_data_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_key, :text, null: false
      add :display_name, :text, null: false
      add :status, :text, null: false, default: "active"
      add :estimated_cost_per_request, :decimal, null: false
      add :hourly_request_limit, :bigint, null: false
      add :daily_request_limit, :bigint, null: false
      add :monthly_request_limit, :bigint, null: false
      add :monthly_spend_limit, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:acquisition_data_providers, [:provider_key],
             name: "acquisition_data_providers_unique_provider_key_index"
           )

    create table(:acquisition_budget_usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :provider_id,
          references(:acquisition_data_providers,
            column: :id,
            name: "acquisition_budget_usages_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :window_kind, :text, null: false
      add :window_started_at, :utc_datetime_usec, null: false
      add :request_count, :bigint, null: false, default: 0
      add :estimated_spend_usd, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :acquisition_budget_usages,
             [:provider_id, :window_kind, :window_started_at],
             name: "acquisition_budget_usages_unique_provider_window_index"
           )

    create constraint(
             :acquisition_budget_usages,
             :acquisition_budget_usages_window_kind_invariant,
             check: """
               window_kind IN ('hour', 'day', 'month')
             """
           )

    create constraint(
             :acquisition_budget_usages,
             :acquisition_budget_usages_nonnegative_invariant,
             check: """
               request_count >= 0 AND estimated_spend_usd >= 0 AND estimated_spend_usd < 1000000000
             """
           )

    create constraint(:acquisition_data_providers, :acquisition_data_providers_identity_invariant,
             check: """
               btrim(provider_key) <> '' AND btrim(display_name) <> ''
             """
           )

    create constraint(:acquisition_data_providers, :acquisition_data_providers_status_invariant,
             check: """
               status IN ('active', 'disabled')
             """
           )

    create constraint(:acquisition_data_providers, :acquisition_data_providers_cost_invariant,
             check: """
               estimated_cost_per_request >= 0 AND estimated_cost_per_request < 1000000000
             """
           )

    create constraint(
             :acquisition_data_providers,
             :acquisition_data_providers_request_limits_invariant,
             check: """
               hourly_request_limit > 0 AND daily_request_limit > 0 AND monthly_request_limit > 0 AND hourly_request_limit <= daily_request_limit AND daily_request_limit <= monthly_request_limit
             """
           )

    create constraint(
             :acquisition_data_providers,
             :acquisition_data_providers_spend_limit_invariant,
             check: """
               monthly_spend_limit >= 0 AND monthly_spend_limit <= 50
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_spend_limit_invariant
                   )

    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_request_limits_invariant
                   )

    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_cost_invariant
                   )

    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_status_invariant
                   )

    drop_if_exists constraint(
                     :acquisition_data_providers,
                     :acquisition_data_providers_identity_invariant
                   )

    drop_if_exists constraint(
                     :acquisition_budget_usages,
                     :acquisition_budget_usages_nonnegative_invariant
                   )

    drop_if_exists constraint(
                     :acquisition_budget_usages,
                     :acquisition_budget_usages_window_kind_invariant
                   )

    drop constraint(:acquisition_budget_usages, "acquisition_budget_usages_provider_id_fkey")

    drop_if_exists unique_index(
                     :acquisition_budget_usages,
                     [:provider_id, :window_kind, :window_started_at],
                     name: "acquisition_budget_usages_unique_provider_window_index"
                   )

    drop table(:acquisition_budget_usages)

    drop_if_exists unique_index(:acquisition_data_providers, [:provider_key],
                     name: "acquisition_data_providers_unique_provider_key_index"
                   )

    drop table(:acquisition_data_providers)
  end
end
